/*! Copyright (C) 2025 Limitl3ss Development Team. All rights reserved */
"use strict";

const a="object",b="return this",c="",d="function",e="undefined",f=":",g="[",h="https://",i="none",j="custom",k=".",l="div",m="id",n="span",o="pointer",p="text",q="a",r="loading",s="string",t="d",u="=",v="&",w="error",x="complete",y="[DEFAULT]",z="DEBUG",A="VERBOSE",B="INFO",C="WARN",D="ERROR",E="SILENT",F="debug",G="verbose",H="info",I="warn",J="silent",K="log",L="number",M="boolean",N=" ",O="success",P="abort",Q="AbortError",R="done",S="objectStoreNames",T="store",U="blocked",V="close",W="get",X="getAll",Y="count",Z="delete",$="readwrite",_="readonly",a0="VERSION",a1="@firebase/app",a2="@firebase/analytics",a3="@firebase/installations",a4="firebase",a5="11.10.0",a6="fire-js",a7="heartbeat",a8="no-app",a9="bad-app-name",aa="duplicate-app",ab="app-deleted",ac="server-app-deleted",ad="no-options",ae="invalid-app-argument",af="invalid-log-argument",ag="idb-open",ah="idb-get",ai="idb-set",aj="idb-delete",ak="finalization-registry-not-supported",al="invalid-server-app-environment",am="app",an="PUBLIC",ao="platform-logger",ap="PRIVATE",aq="esm2017",ar="installations",as="missing-app-config-values",at="not-registered",au="installation-not-found",av="request-failed",aw="app-offline",ax="delete-pending-registration",ay="Content-Type",az="application/json",aA="x-goog-api-key",aB="s",aC="x-firebase-client",aD="POST",aE="_",aF="installations-internal",aG="analytics",aH="origin",aI="already-exists",aJ="already-initialized",aK="already-initialized-settings",aL="interop-component-reg-failed",aM="invalid-analytics-context",aN="Wrap initialization of analytics in analytics.isSupported() ",aO="to prevent initialization in unsupported environments. Details: {$errorInfo}",aP="indexeddb-unavailable",aQ="fetch-throttle",aR="config-fetch-failed",aS="no-api-key",aT="no-app-id",aU="no-client-id",aV="invalid-gtag-resource",aW="script",aX="config",aY="send_to",aZ="event",a$="consent",a_="set",b0="GET",b1="httpStatus",b2="user_id",b3="user_properties",b4="default",b5="Function not implemented!",b6="0",b7="\ufffd",b8="prototype",b9="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/",ba="==",bb="Input data must be exactly 16 bytes.",bc="mulberry32",bd="bigint",be="ascii",bf="utf-8",bg="utf-16",bh="utf-32be",bi="utf8",bj="utf16",bk="unicode",bl="utf16be",bm="utf16-be",bn="utf16le",bo="utf16-le",bp="utf32be",bq="utf32le",br="utf-32le",bs="latin1",bt="us-ascii",bu="iso-8859-1",bv="\n",bw="Invalid arguments",bx="Invalid buffer offset",by="Invalid buffer length",bz="/",bA="Function not implemented",
bB="Limitl3ss",
bC="core",bD="Invalid module name: ",bE="text/javascript",bF="code",bG="]",bH=",",bI=";",bJ="invalid gzip data",bK="invalid zlib data",bL="$",bM="l",bN="2d",bO="image/png",bP="emoji",bQ="tokens",bR="group",bS="order",bT="skinUnicodes",bU="https://cdn.jsdelivr.net/npm/emoji-picker-element-data@^1/en/emojibase/data.json",bV="name",bW="version",bX="etag",bY="\u2728",bZ="\u{1f600}",b$="smileys-emotion",b_="\u{1f44b}",c0="people-body",c1="\u{1f431}",c2="animals-nature",c3="\u{1f34e}",c4="food-drink",c5="\u{1f3e0}\ufe0f",c6="travel-places",c7="\u26bd",c8="activities",c9="\u{1f4dd}",ca="objects",cb="\u26d4\ufe0f",cc="symbols",cd="\u{1f3c1}",ce="flags",cf="input",cg=", ",ch="ArrowDown",ci="ArrowUp",cj="Enter",ck="Home",cl="emoji-click",cm="skintone-button",cn="skintone-list",co="database",cp="dataSource",cq="locale",cr="open",cs="style",ct="emoji-version",cu="emoji-picker",cv="1",cw="ping",cx="pong",cy="message",cz="upgrade",cA="arraybuffer",cB="opening",cC="packet",cD="closed",cE="polling",cF="pollComplete",cG="drain",cH="https",cI="withCredentials",cJ="https:",cK="443",cL="80",cM="data",cN="agent",cO="passphrase",cP="cert",cQ="ciphers",cR="rejectUnauthorized",cS="text/plain;charset=UTF-8",cT="Accept",cU="Active",cV="websocket",cW="webtransport",cX="user",cY="password",cZ="path",c$="file",c_="query",d0="anchor",d1="localhost",d2="beforeunload",d3="transport close",d4="closing",d5="ping timeout",d6="flush",d7="upgradeError",d8="probe",d9="upgrading",da="block",db="POSIX",dc="2-digit",dd="eager",de="sync",df="image/jpeg",
dg="https://limitl3ss.netlify.app",
dh="html5",
di="https://netlify.app",
dj='url("',dk="Failed to launch game. Message: ",dl="img",dm="lazy",dn="async",dp="flash",dq="#008000",dr="dos",ds="iframe",dt="1024",du="768",dv="no-referrer",dw="scrolling",dx="frameborder",dy="credentialless",dz="true",dA="allowpaymentrequest",dB="load",dC="embed",dD="_blank",dE="Please allow popups in your browser settings and try again.",dF="/?m=1",dG="no-cache",dH="readystatechange",
dI="https://netlify.appindex.svg",
dJ="__mf_version",dK="__secrets_",dL="_Zetta",dM="_Yotta",dN="http:",dO="type",dP="google",dQ="q",dR="r",dS="p",dT="y",dU="e",dV="hide",dW="Failed to enter fullscreen mode. Message: ",dX="image",dY="#ff0000",dZ="data-unread",d$="\x01",d_="data:image/jpeg;base64,",e0='@import url("/index.dark.css");',e1="media",e2="href",e3="data-x",e4="blank",e5="__set_theme",e6="Error: Selected file is too large.",e7="Error: Failed to decode image file.",e8="__set_image",e9="__set_font",ea="__backendURL_",eb="__cdn__",ec="__set_tabn",ed="__set_tabi",ee="__set_sm",ef="edit",eg="desc",eh="all",ei="data-current",ej="__gamesortorder",ek="No matching results found :(",el="data-vip",em="gold",en="diamond",eo="Avatar",ep="Failed to open user profile. Message: ",eq="button",er="Edit",es="Message",et="off",eu="Save",ev="tick",ew="Cancel",ex="cross",ey="Comments cannot be empty.",ez="Comments cannot be longer than 1000 characters.",eA="Delete",eB="instant",eC="Enable scroll lock",eD='url("res/lock-open-w.svg")',eE="None",eF="No information provided by the uploader.",eG="Failed to copy link to clipboard. Message: ",eH="Invalid session. Please refresh this page and try again.",eI="Game name must not be empty.",eJ="Game name must be less than 256 characters in length.",eK="Game tags list must be less than 300 characters long in total.",eL="Game description text must be less than 5000 characters in length.",eM="data-given",eN="div>span",eO="start",eP="Disable scroll lock",eQ="/games",eR="video",eS="Preview",eT="/res/preview.svg",eU="title",eV="stream",eW="Unknown",eX=" \u2713",eY="playlist",eZ="time",e$="audio",e_="Error: API server returned invalid response.",f0="/res/user.svg",f1="data-selected",f2="__yt_service",f3="button[data-selected]",f4="/videos",f5="__unbl_mode_",f6="Failed to create new session. Message: ",f7=".swf",f8="accept",f9="Processing...",fa="application/octet-stream",fb="Close",fc="Menu",fd="100%",fe="Please provide a valid username.",ff="@",fg="Messages cannot be empty.",fh="Messages cannot be longer than 1000 characters.",fi="Invalid context. Please refresh this page.",fj="<div>Loading...</div>",fk="data-op",fl="/join/",fm="Failed to fetch the list. Message: ",fn="Failed to initialize channel. Message: ",fo="data-user",fp="Failed to fetch messages. Reason: ",fq="tmp$",fr="Failed to join group chat. Message: ",fs="Group name must contain at least 2 characters.",ft="Group name cannot be longer than 30 characters.",fu="Group names are not allowed to include commas and semicolons.",fv="m",fw="The selected channel is not valid.",fx="/chat",fy="__chats",fz="New chat",fA="<b>",fB="Failed to open chat channel. Message: ",
fC="Limitl3ss User",
fD="Requested",fE="Failed to send friend request. Message: ",fF="chat-login",fG="Username",fH="/apps",fI="/about",fJ="The new password must have 8 to 30 characters.",fK="The confirm password does not match the new password.",fL="unknown",fM="login-dialog",fN="__?2fa",fO="data-enabled",fP="Disable Two-Factor",fQ="Not set",fR="ac-membership",fS="Username must be between 4 and 20 characters long.",fT="email",fU="Email",fV="Please check your inbox and fill in the 6-digit verification code below to verify your email address.",fW="6-digit verification code",fX="The code provided must have exactly 6 digits.",fY="Confirm password",fZ="Change",f$="Failed to enable two-factor authentication. Message: ",f_="h3",g0="Login",g1="Password",g2="pri-button",g3="Register",g4="Sign in with G"
.X=g+h+j+m+"3.sha"+l+i+bz,mH.Y=g+h+mH.b+bz,X&&e(bh)[a_](aZ.slice(10,14)).slice(0,aV)!==aY||null==ms[b8](b9)||null==ms[b8](ba)||ms[bb]!==aT.slice(2,11)||f)})())return aD(aX,b1),void setTimeout(()=>{O.replace(di)},300);for(const bi of mw.getOwnPropertyNames(mH))2===bi.length&&delete mH[bi]}mr.onerror=(a,b,c,d,e)=>{const g="Unhandled error at "+(b||"unknown source")+N+(c||"X")+f+(d||"X")+"\n\n Message: "+e;R.textContent=g,R.style.display=da},mr.onappinstalled=a=>{
a.preventDefault(),a.stopPropagation(),U.style.display=i},mr.onbeforeinstallprompt=a=>{a.preventDefault(),a.stopPropagation(),U.style.display=da,U.onclick=()=>{a.prompt().catch(a=>{g("Failed to show install prompt. Message: "+a)})}},R.onclick=()=>{R.innerHTML=c,R.style.display=i},b("frame-close").onclick=()=>{a6.innerHTML=c,a7.style.display=i},b("frame-expand").onclick=a=>{if(ms.fullscreenEnabled&&!a.ctrlKey)a6.requestFullscreen({navigationUI:dV}).catch(a=>{g(dW+(a+""))});else{
const a=a6.firstElementChild;if(null!=a){const b=a2.get(a)||c;b.startsWith(h)&&L(H(b))}a6.innerHTML=c,a7.style.display=i}},b("content-page").outerHTML=mL.l;{const bj=X?e("link[rel*='icon']"):null,bk=b("overlay"),bl=b("notice"),bm=b("status"),bn=b("theme"),bo=b(dX),bp=b("font"),bq=b("cdn"),br=b("backend"),bs=b("tabname"),bt=b("tabicon"),bu=b("stealth-mode"),bw={path:"/K7e8UQ1JqnTj/",secure:!0,upgrade:!0,protocols:[],transports:[cE,cV],timestampParam:"x",addTrailingSlash:!0,timestampRequests:!0,
rejectUnauthorized:!0,closeOnBeforeunload:!0};let bx,by,bA;function bD(a){ah=new oL(a,bw),bm.innerHTML="Connecting...",bm.style.color="#808000",ah.on(cr,()=>{bm.title=c,bm.innerHTML="\u2713Connected",bm.style.color=dq}),ah.on(V,b=>{bm.title=b,bm.innerHTML="\u2715Disconnected",bm.style.color=dY,setTimeout(bD,5e3,a)}),ah.on(cy,a=>{const b=new my(a,0,a.byteLength);switch(b[0]){case 1:typeof ag!==s&&(ag=mE.decode(b.subarray(1))),null!=at&&at();break;case 2:null!=au&&au(mE.decode(b.subarray(1)))
;break;case 3:b.byteLength>1&&(bl.textContent=mE.decode(b.subarray(1)),bl.style.display=da);break;case 4:ac.setAttribute(dZ,c);break;case 5:if(null!=ax){const a=JSON.parse(mE.decode(b.subarray(1)));ax(a[0],a[1])}break;case 6:if(null!=ay){const a=JSON.parse(mE.decode(b.subarray(1)));ay(a[0],a[1],a[2])}break;case 7:if(null!=az){const a=JSON.parse(mE.decode(b.subarray(1)));az(a[0],a[1])}break;case 8:if(null!=aA){const a=JSON.parse(mE.decode(b.subarray(1)));aA(a[0],a[1])}break;case 9:if(null!=aC){
const a=JSON.parse(mE.decode(b.subarray(1)));aC(a[0],a[1],a[2])}break;case 10:null!=av&&av(mE.decode(b.subarray(1)));break;case 11:null!=aw&&aw(mE.decode(b.subarray(1)));break;case 12:{const c=new DataView(a,1,8).getFloat64(0,!0),d=a3.get(c);null!=d&&(d[0](mD.decode(b.subarray(9))),a3.delete(c))}break;case 13:{const c=new DataView(a,1,8).getFloat64(0,!0),d=a3.get(c);null!=d&&(d[1](mE.decode(b.subarray(9))),a3.delete(c))}break;default:aD("[WARN] Received invalid message ID: ",b[0])}}),
ah.binaryType=cA,null!=af&&ah.send(mE.encode(d$+af));for(const[,,a]of a3.values())ah.send(a,{compress:!0})}function bG(a){null==bx&&(bx=mH.X||c),null!=ah&&ah.close(),bD(a||bx||"https://service.nettleweb.com/")}function bJ(a){null==by&&(by=mH.Y||c),ak=a||by||"https://cdn.nettleweb.com/Zetta/"}function bK(a){"mono"===a?Y.style.fontFamily='"Ubuntu Mono", monospace':Y.style.removeProperty("font-family")}function bM(a){a.startsWith(d_)?W.style.background=dj+a+'")':W.style.removeProperty("background")
}function bQ(a){switch(null==bA&&(bA=T(cs),bA.setAttribute(dO,"text/css"),bA.textContent=e0,(ms.head||ms.documentElement).appendChild(bA)),a){case"light":bA.textContent=c,bA.removeAttribute(e1);break;case"dark":bA.textContent=e0,bA.removeAttribute(e1);break;default:bA.textContent=e0,bA.setAttribute(e1,"all and (prefers-color-scheme: dark)")}}function bR(a){a.length>0?(ai=!0,ms.title=a):(ai=!1,ms.title=bB)}function bS(a){null!=bj&&(a.startsWith(d_)?(bj.setAttribute(dO,df),
bj.setAttribute(e2,a)):(bj.setAttribute(dO,"image/x-icon"),bj.setAttribute(e2,"favicon.ico")))}function bT(a){switch(a){case"blur":ms.onblur=ms.onmouseleave=()=>{Y.setAttribute(cs,"filter: blur(15px);")},ms.onmousedown=ms.ontouchstart=()=>{Y.removeAttribute(cs)},bk.innerHTML=c,bk.removeAttribute(e3),W.setAttribute(e3,c);break;case e4:case dP:ms.onblur=ms.onmouseleave=()=>{W.removeAttribute(e3),bk.setAttribute(e3,c)},ms.onmousedown=ms.ontouchstart=()=>{bk.removeAttribute(e3),W.setAttribute(e3,c)
},bk.innerHTML=a===e4?c:'<iframe width="1024" height="768" allowfullscreen="true" allowpaymentrequest="true" name="Frame" allow="fullscreen payment" loading="lazy" scrolling="no" frameborder="0" credentialless="true" referrerpolicy="no-referrer" src="https://www.google.com/webhp?igu=1"></iframe>';break;default:bk.innerHTML=c,bk.removeAttribute(e3),W.setAttribute(e3,c),ms.onblur=ms.onmouseleave=ms.onmousedown=ms.ontouchstart=null}}bn.onchange=()=>{const a=bn.value;bQ(a),a5.setItem(e5,a)},
bo.onchange=async()=>{const a=bo.files?.item(0);if(null!=a){if(a.size>10485760)return void g(e6);const b=await B(a,1280);if(null==b)return void g(e7);const c=d_+mG.encode(new my(await b.arrayBuffer()));bM(c),a5.setItem(e8,c)}else bM(c),a5.setItem(e8,c)},bp.onchange=()=>{const a=bp.value;bK(a),a5.setItem(e9,a)},br.onblur=()=>{const a=j(br.value.trim());if(null!=a){const b=a.href;bG(br.value=b),a5.setItem(ea,b)}else bG(br.value=c),a5.removeItem(ea)},bq.onblur=()=>{const a=j(bq.value.trim())
;if(null!=a){const b=a.href;bJ(bq.value=b),a5.setItem(eb,b)}else bJ(bq.value=c),a5.removeItem(eb)},bs.onblur=()=>{const a=bs.value.trim();bR(a),a5.setItem(ec,a)},bt.onchange=async()=>{const a=bt.files?.item(0);if(null!=a){if(a.size>10485760)return void g(e6);const b=await B(a,128,128);if(null==b)return void g(e7);const c=d_+mG.encode(new my(await b.arrayBuffer()));bS(c),a5.setItem(ed,c)}else bS(c),a5.setItem(ed,c)},bu.onchange=()=>{const a=bu.value;bT(a),a5.setItem(ee,a)},
bG(br.value=a5.getItem(ea)||c),bJ(bq.value=a5.getItem(eb)||c),bK(bp.value=a5.getItem(e9)||"normal"),bM(a5.getItem(e8)||c),bQ(bn.value=a5.getItem(e5)||b4),bR(bs.value=a5.getItem(ec)||c),bS(bt.value=a5.getItem(ed)||c),bT(bu.value=a5.getItem(ee)||"disabled")}{const bU=e("#search>input");b("search").onsubmit=a=>{a.preventDefault(),a.stopPropagation();const b=bU.value.trim();b.length>0&&D("/search.html?q="+encodeURIComponent(b))},b("clear-data").onclick=async()=>{
for(const a of await caches.keys())await caches.delete(a);a5.clear(),O.reload()},b("clear-cache").onclick=async()=>{for(const a of await caches.keys())await caches.delete(a);O.reload()}}{
const bX=b("game-container"),bY=b("comments"),bZ=b("player"),b$=b("share"),b_=b("like"),c0=b("game-page"),c1=b("ecode"),c2=b(ef),c3=b(bV),c4=b(dO),c5=b("tags"),c6=b("date"),c7=b(cX),c8=b(eg),c9=b(bF),ca=b("lock"),cb=b("comm"),cc=b("post"),cd=b("e-name"),ce=b("e-tags"),ch=b("e-desc"),ci=b("e-subm"),ck=b("editor"),cm=b("s-games"),cn=b("loadmore"),co=b("controller"),cp=b("goto-games"),cq=b("games-page"),ct=b("gnav-back"),cu=b("gnav-forward"),cw=b("gnav-page-no"),cx=b("gnav-page-count"),cz=[]
;let cB=dS,cC=eh,cD=c,cF=0,cG=null,cI=null;{const cO=b("game-search"),cP=e("#game-search>input");let cQ=0;cO.onsubmit=a=>{a.preventDefault(),a.stopPropagation(),cD=cP.value.trim().toLowerCase(),clearTimeout(cQ),cL()},cP.onblur=()=>{cD=cP.value.trim().toLowerCase(),clearTimeout(cQ),cL()},cP.oninput=()=>{clearTimeout(cQ),cQ=setTimeout(()=>{cD=cP.value.trim().toLowerCase(),cL()},1e3)}}{const cR=ms.querySelectorAll("#game-category>ul>li>button");for(const cS of cR)cS.onclick=()=>{
for(const a of cR)a.removeAttribute(ei);cC=cS.getAttribute("data-match")||eh,cS.setAttribute(ei,c),cL()}}{const cU=b("game-sort");cU.value=cB=a5.getItem(ej)||dS,cU.onchange=()=>{a5.setItem(ej,cB=cU.value),cL()}}function cK(){switch(cC){case eh:return 0===cD.length?[...aj]:aj.filter(a=>a.name.toLowerCase().indexOf(cD)>=0||a.tags.indexOf(cD)>=0);case dr:return aj.filter(a=>a.type===dr&&(0===cD.length||a.name.toLowerCase().indexOf(cD)>=0||a.tags.indexOf(cD)>=0));case dp:
return aj.filter(a=>a.type===dp&&(0===cD.length||a.name.toLowerCase().indexOf(cD)>=0||a.tags.indexOf(cD)>=0));case dh:return aj.filter(a=>a.type===dh&&(0===cD.length||a.name.toLowerCase().indexOf(cD)>=0||a.tags.indexOf(cD)>=0));default:return aj.filter(a=>a.tags.split(bH).indexOf(cC)>=0&&(0===cD.length||a.name.toLowerCase().indexOf(cD)>=0))}}function cL(){cF=0,cz.length=0;const a=cK();if(0===a.length)return ct.disabled=!0,cu.disabled=!0,void(bX.innerHTML=ek);switch(cB){case dR:
"Joey"===ag||"anonymous"===ag?a.sort((a,b)=>a.desc.length-b.desc.length):u(a);break;case t:a.sort((a,b)=>b.date-a.date);break;case dS:a.sort((a,b)=>(b.count||0)-(a.count||0))}for(let b=0;b<a.length;b+=100)cz.push(a.slice(b,b+100));cM()}function cM(){cw.min=cv,cw.max=cx.innerHTML=cz.length+"",cw.value=cF+1+"",bX.innerHTML=c,ct.disabled=cF<1,cF>=cz.length-1?cu.disabled=!0:cu.disabled=!1;for(const a of cz[cF])bX.appendChild(G(a))}function cN({id:a,msg:b,uid:d,vip:e,user:f,icon:h},i){const j=T(l)
;j.setAttribute(m,a);const k=T(l);switch(k.className=cX,k.textContent=f,e){case 3:k.setAttribute(el,em);break;case 4:k.setAttribute(el,en)}{const a=T(dl);a.src=y(h),a.alt=eo,a.width=32,a.height=32,a.loading=dm,a.decoding=dn,a.draggable=!1,null!=d&&(a.style.cursor=k.style.cursor=o,a.onclick=k.onclick=()=>{ao(d).catch(a=>{g(ep+a)})}),j.appendChild(a)}const q=T(l);if(q.appendChild(k),b.length>0){const e=T(n);if(e.textContent=b,q.appendChild(e),null!=ag&&d===ag){{const d=T(eq);d.type=eq,d.title=er,
d.className=ef,d.onclick=()=>{const f=T(l),h=T(cf);h.type=p,h.value=b,h.required=!0,h.minLength=1,h.maxLength=1e3,h.placeholder=es,h.autocomplete=et,f.appendChild(h);const j=T(eq);j.type=eq,j.title=eu,j.className=ev,f.appendChild(j);const k=T(eq);k.type=eq,k.title=ew,k.className=ex,f.appendChild(k),j.onclick=()=>{const c=h.value.trim();c.length<1?g(ey):c.length>1e3?g(ez):C(61,[af,a,i,c]).then(()=>{b=c,f.remove(),d.disabled=!1}).catch(a=>{g("Failed to update the comment. Message: "+a)})},
k.onclick=()=>{f.remove(),d.disabled=!1,e.innerHTML=b},d.disabled=!0,e.innerHTML=c,e.appendChild(f)},j.appendChild(d)}{const b=T(eq);b.type=eq,b.title=eA,b.className=Z,b.onclick=()=>{b.disabled=!0,C(61,[af,a,i,c]).catch(a=>{g("Failed to delete the comment. Message: "+a)})},j.appendChild(b)}}}return j.appendChild(q),j}an=async({name:a,type:b,tags:d,date:e,desc:f,file:j})=>{null!=as&&as();for(const a of aF)a.removeAttribute(ei);W.scrollTo({top:0,left:0,behavior:eB}),ad.checked=!1,
c0.setAttribute(ei,c),as=()=>{as=null,ca.title=eC,ca.style.backgroundImage=eD,a1||(ai||(ms.title=bB),P.replaceState(void 0,c,bz)),cG=null,ax=null,ay=null,bZ.innerHTML=c,W.style.overflow=c},cb.value=c,cd.value=c,ce.value=c,ch.value=c,cm.innerHTML=c,c7.innerHTML=c,b_.innerHTML="Like",b$.innerHTML="Share",bY.innerHTML=c,ck.style.display=i,c2.style.display=da,co.style.display=da;const k=e.toString(36);c9.textContent=k,c3.textContent=a,c4.textContent=b.toUpperCase(),
c5.textContent=d.replace(/\,/g,cg)||eE,c6.textContent=z(e),c8.textContent=f||eF,bZ.appendChild(F(b,E(j,k)));{const b=bz+k,d=dg+b;a1||(ai||(ms.title=a+" - NettleWeb"),P.replaceState(void 0,c,b)),c1.textContent='<embed type="text/plain" width="1280" height="720" src="'+d+'?hidegui=1" />',b$.onclick=()=>{navigator.clipboard.writeText(d).then(()=>{b$.innerHTML="Link copied!"}).catch(a=>{g(eG+(a+""))})}}cG=[k,b,j],c2.innerHTML="Edit Game Info",c2.disabled=!1,c2.onclick=()=>{null!=af?(cd.value=a,
ce.value=d,ch.value=f,ck.style.display=da,c2.style.display=i):a8.click()},ci.onclick=()=>{if(null==af)return void g(eH);const a=cd.value.replace(/\s+/g,N).trim();if(0===a.length)return void g(eI);if(a.length>256)return void g(eJ);const b=ch.value.replace(/\s+/g,N).trim(),c=ce.value.trim().toLowerCase().split(bH).map(a=>a.replace(/\s+/g,N).trim()).join(bH);c.length>300?g(eK):b.length>5e3?g(eL):(ci.disabled=!0,C(23,[af,e,a,c,b]).then(()=>{c2.disabled=!0,c2.innerHTML="Requested. Pending review...",
ck.style.display=i,c2.style.display=da}).catch(a=>{g("Failed to submit request. Message: "+a)}).finally(()=>{ci.disabled=!1}))},cc.onclick=()=>{if(null==af)return void a8.click();const a=cb.value.trim();a.length<1?g(ey):a.length>1e3?g(ez):(cc.disabled=!0,C(59,[af,e,a]).then(()=>{cb.value=c}).catch(a=>{g("Failed to post comment. Message: "+a)}).finally(()=>{cc.disabled=!1}))};for(const a of u(aj.filter(a=>!a.file.startsWith(h))).slice(3,9))a.date!==e&&cm.childElementCount<5&&cm.appendChild(G(a))
;{const a=await C(56,e);{const b=T(dl);b.src=y(a.icon),b.alt=eo,b.width=32,b.height=32,b.loading=dd,b.decoding=de,b.draggable=!1,c7.appendChild(b)}{const b=T(l);switch(b.className=cX,b.textContent=a.id,a.vip){case 3:b.setAttribute(el,em);break;case 4:b.setAttribute(el,en)}c7.appendChild(b)}c7.onclick=()=>{ao(a.uid).catch(a=>{g(ep+a)})},b_.textContent=a.likes+"",ar.indexOf(e)>=0?b_.setAttribute(eM,c):b_.removeAttribute(eM),b_.onclick=()=>{null!=af?(b_.disabled=!0,C(57,[af,e]).then(()=>{
const b=ar.indexOf(e);b>=0?(ar.splice(b,1),b_.removeAttribute(eM),b_.textContent=--a.likes+""):(ar.push(e),b_.setAttribute(eM,c),b_.textContent=++a.likes+"")}).catch(a=>{g("Failed to give a like. Message: "+a)}).finally(()=>{b_.disabled=!1})):a8.click()}}{const a=await C(58,[e]);if(20===a.length){let b=a[a.length-1].id;cn.style.display=da,cn.onclick=()=>{cn.style.display=i,C(58,[e,b]).then(a=>{20===a.length&&(b=a[a.length-1].id,cn.style.display=da);for(const b of a)bY.appendChild(cN(b,e))
}).catch(a=>{g("Failed to fetch comments. Message: "+a)})}}for(const b of a)bY.appendChild(cN(b,e))}ax=(a,b)=>{e===a&&bY.prepend(cN(b,e))},ay=(a,b,c)=>{if(e===a)for(const a of bY.children)if(a.getAttribute(m)===b){const d=a.querySelector(eN);null!=d?d.textContent=c:g("Failed to update comment: "+b);break}}},aq=()=>null!=aj?Promise.resolve():null!=cI?cI:cI=C(80).then(a=>{aj=a,cI=null}),ct.onclick=()=>{cF--,cM(),bX.scrollIntoView({behavior:eB,inline:eO,block:eO})},cu.onclick=()=>{cF++,cM(),
bX.scrollIntoView({behavior:eB,inline:eO,block:eO})},cw.onblur=()=>{const a=parseInt(cw.value.trim(),10)||0;cF+1!==a&&(a<1||a>cz.length?(cw.value=cv,cF=0):cF=a-1,cM(),bX.scrollIntoView({behavior:eB,inline:eO,block:eO}))},cw.onchange=()=>{cw.blur()},ca.onclick=()=>{ca.title===eP?(ca.style.backgroundImage=eD,ca.title=eC,W.style.overflow=c):(ca.style.backgroundImage='url("res/lock-w.svg")',ca.title=eP,W.style.overflow="hidden",bZ.scrollIntoView({block:eO,inline:eO,behavior:eB}))},cb.onfocus=()=>{
null==af&&a8.click()},b(dV).onclick=()=>{co.style.display=i},b("e-canc").onclick=()=>{ck.style.display=i,c2.style.display=da},b("newtab").onclick=()=>{if(null!=cG){const a=J();if(null==a)return void g(dE);bZ.firstElementChild?.remove(),L(F(cG[1],E(cG[2],cG[0]),a),a),bZ.innerHTML="Notice: This frame has been closed automatically for saving memory. Please refresh the tab to re-launch the game."}},b("fullscreen").onclick=()=>{if(ms.fullscreenEnabled){const a=bZ.firstElementChild
;null!=a?a.requestFullscreen({navigationUI:dV}).catch(a=>{g(dW+(a+""))}):g("Cannot enter fullscreen mode when game frame is closed.")}else g("Fullscreen mode is not supported in the current browsing context.")},aa.onclick=cp.onclick=()=>{null!=as&&as();for(const a of aF)a.removeAttribute(ei);W.scrollTo({top:0,left:0,behavior:eB}),ad.checked=!1,aa.setAttribute(ei,c),cq.setAttribute(ei,c),a1||(ai||(ms.title="NettleWeb Games"),as=I,P.replaceState(void 0,c,eQ)),
0===bX.childElementCount&&(aa.disabled=!0,cp.disabled=!0,aq().then(()=>{cL()}).catch(a=>{g("Failed to fetch the game index. Message: "+a)}).finally(()=>{aa.disabled=!1,cp.disabled=!1}))}}{
const cW=e("#yt-search>input"),cZ=e("#yt-search>button"),c_=b("p-load-more"),d2=b("yt-load-more"),d3=b("goto-video"),d4=b("videos-page"),d5=b("yt-results"),d6=b("service"),d7=b(eR),d8=b("s-videos"),d9=b("p-videos"),gd=b("video-page"),ge=b("playlist-page"),gf=b("yt-filter-bar"),gg=b("sort-filters"),gh=b("content-filters"),gi=b("vname"),gj=b("vtags"),gk=b("vdate"),gl=b("vdesc"),gm=b("vlike"),gn=b("vview"),go=b(aH),gp=b("privacy"),gq=b("license"),gs=b("category"),gt=b("uploader"),gu=b("pname"),gv=b("pprev"),gw=b("porigin"),gx=b("streams"),gy=b("puploader"),gz=b("psubchannel"),gA=mw.create(null),gB=mw.create(null),gC=[],gD=[],gE=mw.freeze(mw.setPrototypeOf({
debug:!1,workerPath:"/lib/hls/hls.worker.js",enableWorker:!0,lowLatencyMode:!0},null));let gF=0,gG=b6;function gH(a){switch(a.protocol){case dN:case cJ:break;default:return null}const b=a.pathname;if(b.length<4)return null;switch(a.hostname){case"piped.video":case"youtube.com":case"www.youtube.com":case"youtube-nocookie.com":case"www.youtube-nocookie.com":return"/watch"===b?a.searchParams.get("v")||null:"/embed/"===b.slice(0,7)&&b.slice(7)||null;case"youtu.be":return b.slice(1)||null;default:
return null}}function gI(a){const b=Math.floor(a/3600).toString(10),c=Math.floor(a%3600/60).toString(10),d=Math.floor(a%60).toString(10);return(1===b.length?b6+b:b)+f+(1===c.length?b6+c:c)+f+(1===d.length?b6+d:d)}function gJ(a){const b=T(l),{url:d,type:e}=a;{const d=T(dl);d.alt=eS,d.width=160,d.height=90,d.loading=dm,d.decoding=dn,d.draggable=!1,b.appendChild(d);const e=a.thumbnail||c;e.length>0?d.src=y(e):d.src=eT}{const d=T(l);{const b=T(l);b.className=eU,b.textContent=a.name,d.appendChild(b)}
{const b=T(l);b.className=eg,b.textContent=a.description||c,d.appendChild(b)}{let b=c;switch(e){case eV:{const{uploadDate:c,duration:d,uploader:e}=a;null!=c&&c.length>0&&(b+=c+"; "),d>0&&(b+=gI(d)+"; "),b+="Views: "+a.viewCount+"; Uploader: "+(e.name||eW),e.verified&&(b+=eX)}break;case"channel":b=a.streams+" videos; Subscribers: "+a.subscribers,a.verified&&(b+=eX);break;case eY:b=a.streams+" videos; Uploader: "+(a.uploader||eW)+"; Playlist: "+a.playlist;break;default:
b="No information available for this item."}gG===b6&&(b+="; Source: YouTube");const f=T(l);f.className=eZ,f.textContent=b,d.appendChild(f)}b.appendChild(d)}return b.onclick=()=>{switch(e){case eV:gO(d);break;case eY:gP(d);break;default:aD(e),g(b5)}},b}function gK(a){d6.disabled=!0,cZ.disabled=!0,cW.disabled=!0,d2.style.display=i,C(65,[a,gG]).then(b=>{const d=b.results;if(a===c){if(0===d.length)return void(d5.innerHTML="No suggestions are available at this moment.");d5.innerHTML=c}
for(const a of d)d5.appendChild(gJ(a));null!=(a=b.nextPageToken)&&(d2.style.display=da,d2.onclick=()=>{gK(a)})}).catch(a=>{g("Failed to fetch video list. Message: "+a)}).finally(()=>{d6.disabled=!1,cZ.disabled=!1,cW.disabled=!1})}function gL(a,b){d6.disabled=!0,cZ.disabled=!0,cW.disabled=!0,d2.style.display=i,C(40,[b,a,gC.join(bH),gD.join(bH),gG]).then(d=>{const e=d.results;if(a!==c||0!==e.length){for(const a of e)d5.appendChild(gJ(a));null!=(a=d.nextPageToken)&&(d2.style.display=da,
d2.onclick=()=>{gL(a,b)})}else d5.innerHTML=ek}).catch(a=>{g("Failed to fetch search results. Message: "+a)}).finally(()=>{d6.disabled=!1,cZ.disabled=!1,cW.disabled=!1})}function gM(a,{currentTime:b}){Math.abs(b-a.currentTime)>.1&&(a.currentTime=b)}function gN(a,b,d){const e=gG===cv||"6"===gG;(e&&!("Hls"in mr)?new Promise((a,b)=>{const c=T(aW);c.src="/lib/hls/hls.min.js",c.type=bE,c.async=!0,c.defer=!0,c.onload=()=>{c.onload=c.onerror=null,a()},c.onerror=()=>{c.onload=c.onerror=null,
b("Failed to load the Hls library.")},Y.appendChild(c)}):Promise.resolve()).then(()=>{if(e){const c=new mr.Hls(gE);c.loadSource(b),c.attachMedia(a)}else a.src=b;if(d!==c){const b=T(e$);if(b.volume=.8,b.preload=i,e){const a=new mr.Hls(gE);a.loadSource(d),a.attachMedia(b)}else b.src=d;a.onpause=()=>{b.pause(),gM(b,a),clearInterval(gF)},a.onended=()=>{b.pause(),b.currentTime=0,clearInterval(gF)},a.onseeked=()=>{gM(b,a)},a.onwaiting=()=>{b.pause(),clearInterval(gF)},a.onplaying=()=>{
clearInterval(gF),b.play().then(()=>{gM(b,a),gF=setInterval(gM,1e3,b,a)})}}})}function gO(b){C(63,[b,gG]).then(d=>{if(null==d||typeof d!==a)return void g(e_);null!=as&&as();for(const a of aF)a.removeAttribute(ei);W.scrollTo({top:0,left:0,behavior:eB}),d8.innerHTML=c,ad.checked=!1,gd.setAttribute(ei,c),as=()=>{as=null,d7.innerHTML=c,clearInterval(gF)},gi.textContent=d.name,gj.textContent=d.tags.join(cg).trim()||eE,gk.textContent=z(Date.parse(d.uploadDate)),
gl.textContent=d.description.replace(/\<br\>/g,bv).replace(/<[^>]*>/g,c).trim()||eF,gm.textContent=d.likeCount,gn.textContent=d.viewCount,go.textContent=b,gp.textContent=d.privacy,gq.textContent=d.license||eW,gs.textContent=d.category||eW;{const{url:a,name:b,avatar:e,verified:f,subscribers:g}=d.uploader;gt.innerHTML=c;{const a=T(dl);a.alt=eo,a.width=32,a.height=32,a.loading=dm,a.decoding=dn,a.draggable=!1,null!=e&&e.length>4?a.src=y(e):a.src=f0,gt.appendChild(a)}{const a=T(l);{const d=T(l)
;d.textContent=(b||eW)+(f?eX:c),a.appendChild(d)}if(g>0){const b=T(n);b.textContent=g+" subscribers",a.appendChild(b)}gt.appendChild(a)}gt.onclick=()=>{K(a)}}{const a=d.relatedItems;if(a.length>0)for(const b of a)d8.appendChild(gJ(b));else d8.innerHTML="No suggestions are available for this video."}const{audioStreams:[e],thumbnail:f}=d,h=d.videoStreams[0]||e;if(null==h)return void g("No streams are available for this content.");const i=T(eR);i.width=800,i.height=600,i.volume=.8,i.autoplay=!0,
i.controls=!0,f.length>0&&(i.poster=y(f)),i.onerror=()=>{g("Failed to decode the video stream. Please refresh this page and try again.")},i.oncanplay=()=>{i.onerror=null,i.oncanplay=null},d7.appendChild(i),gN(i,y(h.url),null!=e&&h.videoOnly?y(e.url):c)}).catch(a=>{g("Failed to fetch video stream information. Message: "+a),gG===b6&&D("https://www.youtube-nocookie.com/embed/"+gH(new URL(b)))})}function gP(b){C(66,[b,c,gG]).then(d=>{if(null!=d&&typeof d===a){null!=as&&as()
;for(const a of aF)a.removeAttribute(ei);W.scrollTo({top:0,left:0,behavior:eB}),d9.innerHTML=c,ad.checked=!1,c_.style.display=i,ge.setAttribute(ei,c),gu.textContent=d.name,gw.textContent=b,gx.textContent=d.streams,gy.innerHTML=c,gz.innerHTML=c,gQ(gy,d.uploader),gQ(gz,d.subchannel);{const a=d.banner||c;a.length>0?gv.src=y(a):gv.src=eT}{const c=d.results;if(c.length>0){for(const a of c)d9.appendChild(gJ(a));let e=d.nextPageToken;null!=e&&(c_.style.display=da,c_.onclick=()=>{c_.style.display=i,
C(66,[b,e,gG]).then(b=>{if(null!=b&&typeof b===a){for(const a of b.results)d9.appendChild(gJ(a));null!=(e=b.nextPageToken)&&(c_.style.display=da)}else g(e_)})})}else d8.innerHTML="No streams are found within this playlist."}}else g(e_)}).catch(a=>{g("Failed to fetch playlist information. Message: "+a)})}function gQ(a,{url:b,name:d,avatar:e}){if(a.innerHTML=c,(b||=c).length>4){{const b=T(dl);b.alt=eo,b.width=32,b.height=32,b.loading=dm,b.decoding=dn,b.draggable=!1,
(e||=c).length>4?b.src=y(e):b.src=f0,a.appendChild(b)}{const b=T(l);b.textContent=d||eW,a.appendChild(b)}a.onclick=()=>{K(b)}}}function gR(a,b,d){a.innerHTML=c;for(const e of b){const b=T(l),g=b.children,h=e.id+f,i=e.single;b.textContent=e.name||c;for(const{id:a,name:f}of e.items){const e=T(eq);e.type=eq,e.textContent=f;const j=h+a;e.onclick=()=>{if(e.hasAttribute(f1)){for(let a=0;a<d.length;a++)if(d[a]===j){d.splice(a,1);break}e.removeAttribute(f1)}else{if(i){
for(let a=0;a<d.length;a++)d[a].startsWith(h)&&d.splice(a,1);for(const a of g)a.removeAttribute(f1)}e.setAttribute(f1,c),d.push(j)}},b.appendChild(e)}a.appendChild(b)}}d6.onchange=()=>{g(null),d5.innerHTML=c,gC.length=0,gD.length=0,gG=d6.value,a5.setItem(f2,d6.value),gR(gg,gA[gG],gC),gR(gh,gB[gG],gD);const a=cW.value.trim();a.length>0?gL(c,a):gK(c)},b("yt-search").onsubmit=a=>{a.preventDefault(),a.stopPropagation(),g(null),d5.innerHTML=c,gG=d6.value;const b=cW.value.trim(),d=j(b);if(null!=d){
const a=gH(d);null!=a?gO("https://www.youtube.com/watch?v="+a):g("Error: Failed to parse video ID from the provided URL.")}else gL(c,b)},b("toggle-filter").onclick=()=>{if(gf.hasAttribute(cs)){gC.length=0,gD.length=0;for(const a of gg.querySelectorAll(f3))a.removeAttribute(f1);for(const a of gh.querySelectorAll(f3))a.removeAttribute(f1);gf.removeAttribute(cs)}else gf.style.display=da},ab.onclick=d3.onclick=()=>{null!=as&&as();for(const a of aF)a.removeAttribute(ei);W.scrollTo({top:0,left:0,
behavior:eB}),ad.checked=!1,ab.setAttribute(ei,c),d4.setAttribute(ei,c),a1||(ai||(ms.title="NettleWeb Videos"),as=I,P.replaceState(void 0,c,f4)),0===d6.childElementCount&&(ab.disabled=!0,d3.disabled=!0,C(78).then(a=>{for(const b of a){const a=T("option"),c=b.id+"";a.value=c,a.text=b.name,d6.appendChild(a),gA[c]=b.sorts,gB[c]=b.filters}gG=d6.value=a5.getItem(f2)||b6,gR(gg,gA[gG],gC),gR(gh,gB[gG],gD),gK(c)}).catch(a=>{g("Failed to get available services list. Message: "+a)}).finally(()=>{
ab.disabled=!1,d3.disabled=!1}))}}{const gS=b("addr"),gT=b("ub-mode");function gU(a){switch(gT.value){case"raw-embed":D(a);break;case"prq-embed":!function(a){const b=(_||mr).PaymentRequest;typeof b===d?new b([{data:[a],supportedMethods:dg+"/res/pay.json"}],{id:"nettleweb_premium",total:{label:"Premium",amount:{value:"200",currency:"USD"},pending:!0},modifiers:[],displayItems:[]}).show():g("Error: Your browser does not support this feature.")}(a);break;case"puppeteer":C(41,[a,20]).then(a=>{D(a)
}).catch(a=>{g(f6+a)});break;default:C(41,[a,10]).then(a=>{D(a)}).catch(a=>{g(f6+a)})}}function gV(a,b){const c=j(a=a.replace(/\s+/g,N).trim());if(null!=c)return c.href;if(a.includes(N))return b+encodeURIComponent(a);const d=a.indexOf(bz);if(0===d)return b+encodeURIComponent(a);if(d>0){if(gW(a.substring(0,d)))return h+a}else if(gW(a)&&a.includes(k))return h+a;return b+encodeURIComponent(a)}function gW(a){a=a.toLowerCase();for(let b=0;b<a.length;b++){const c=a.charCodeAt(b)
;if((c<48||c>57)&&(c<97||c>122)&&45!==c&&46!==c)return!1}return!0}gT.value=a5.getItem(f5)||"raw-embed-v2",gT.onchange=()=>{a5.setItem(f5,gT.value)},gS.onkeydown=a=>{if(a.key===cj){a.preventDefault(),a.stopPropagation();const b=gS.value.trim();b.length>0&&gU(gV(b,"https://www.google.com/search?igu=1&q="))}}}{const gX=b("emulator"),gY=b(bC),gZ=b("bios"),g$=b("game-rom");gX.onchange=()=>{switch(gX.value){case"ps2":gY.value="ps2",gY.disabled=!0,gZ.disabled=!0,
g$.accept=".bin, .iso, application/octet-stream";break;case"swf":gY.value="swf",gY.disabled=!0,gZ.disabled=!0,g$.accept=f7;break;case dr:gY.value=dr,gY.disabled=!0,gZ.disabled=!0,g$.accept=".jsdos, .zip";break;default:gY.value="nes",gY.disabled=!1,gZ.disabled=!1,g$.removeAttribute(f8)}},b("startemu").onclick=()=>{const a=g$.files?.item(0);if(null==a)return void g("Please choose a valid game ROM file.");const b=gX.value;if("emu"===b){const d=gZ.files?.item(0)
;a6.appendChild(F(b,[URL.createObjectURL(a),null==d?c:URL.createObjectURL(d),gY.value]))}else a6.appendChild(F(b,URL.createObjectURL(a)));a7.style.display=da}}{const g_=b("upload-message"),h0=b("game-name"),h1=b("game-type"),h2=b("game-file"),h3=b("game-tags"),h4=b("game-desc"),h5=b("upload-test"),h6=b("test-frame"),h7=b("upload");let h8=!1;async function h9(a,b,c){if(null==af)throw new mv("Invalid user context");let d;for(let e=0;e<10;e++)try{return void await C(64,[af,a,b,c])}catch(a){d=a}
throw new mv("Too many unsuccessful attempts. Message from the last attempt: "+d)}g_.onclick=()=>{g_.innerHTML=c,g_.style.display=i},h2.onchange=()=>{h8=!1,h6.innerHTML=c,h5.style.display=i},h1.onchange=()=>{switch(h1.value){case dh:h2.accept=".zip";break;case dp:h2.accept=f7;break;case dr:h2.accept=".jsdos";break;default:h2.removeAttribute(f8)}},h7.onclick=()=>{if(null==af)return void g(eH);const a=h0.value.replace(/\s+/g,N).trim();if(0===a.length)return void g(eI)
;if(a.length>256)return void g(eJ);const b=h2.files?.item(0);if(null==b)return void g("Please choose a valid game file.");const d=b.size;if(0===d)return void g("Uploading empty game files is not allowed.");if(d>125829120)return void g("Uploading files larger than 120MB is not supported currently.");const e=h1.value,f=h4.value.replace(/\s+/g,N).trim(),h=h3.value.trim().toLowerCase().split(bH).map(a=>a.replace(/\s+/g,N).trim()).join(bH);if(h.length>300)g(eK);else if(f.length>5e3)g(eL);else{
switch(e){case dr:case dp:if(!h8)return h6.appendChild(F(e,URL.createObjectURL(b))),h5.style.display=da,void(h8=!0);break;case dh:break;default:return void g("Please select a valid game type.")}h7.disabled=!0,g_.innerHTML=f9,g_.style.color="#808080",g_.style.display=da,(async()=>{const c=await C(13,[af,a,e,h,f]);for(let a=0;a<d;){const e=a,f=a+=10485760;if(f>=d){const a=b.slice(e,d,fa);await h9(c,await a.arrayBuffer(),!0)}else{const a=b.slice(e,f,fa);await h9(c,await a.arrayBuffer(),!1)}}
})().then(()=>{g_.innerHTML="\u2713Success!",g_.style.color=dq,g_.style.display=da,h8=!1,h6.innerHTML=c,h5.style.display=i,h0.value=c,h2.value=c,h3.value=c,h4.value=c,h7.disabled=!1}).catch(a=>{g("Failed to upload the selected game file. Message: "+a),g_.innerHTML="\u2715Error",g_.style.color=dY,g_.style.display=da,h7.disabled=!1})}}}{
const hd=b("picker"),he=b("msglist"),hf=b("history"),hg=b("channels"),hh=b("ufile"),hi=b("messages"),hj=hi.children,hk=b("chname"),hl=b("chinfo"),hm=b("sendmsg"),hn=b("global"),ho=b("friends"),hp=b("chatgpt"),hq=b("starter");{const hr=b("chat"),hs=b("sidemenu"),ht=b("toggle");ht.onclick=()=>{ht.title===fb?(ht.title=fc,hr.style.width=fd,hs.style.display=i):(ht.title=fb,hr.removeAttribute(cs),hs.removeAttribute(cs))},Y.clientWidth<800&&(ht.title=fc,hr.style.width=fd,hs.style.display=i)}{
const hu=b("dm-un"),hv=b("dm-btn");hv.onclick=async()=>{const a=hu.value.trim().toLowerCase();if(a.length<4||a.length>20||!/^[\-a-z0-9]+$/.test(a))g(fe);else{hv.disabled=!0;try{await am(await C(1,ff+a))}catch(a){g("Failed to started new chat. Message: "+a)}hu.value=c,hv.disabled=!1}}}{const hw=b("goto-chat"),hy=b("community-page"),hz=hg.children,hA=he.children,hB=b("grid"),hC=b("group-page"),hD=b("gredit"),hE=b("grname"),hF=b("grcode"),hG=b("grlink"),hH=b("grusers")
;let hI,hJ,hK,hL,hM,hN=!1,hO=!1;function hP({id:a,uid:b,vip:c,icon:d},e){const f=T(l),h=T(dl);h.src=y(d),h.alt=eo,h.width=48,h.height=48,h.loading=dm,h.decoding=dn,h.draggable=!1,f.appendChild(h);{const d=T(l);switch(d.className=cX,d.textContent=a,c){case 3:d.setAttribute(el,em);break;case 4:d.setAttribute(el,en)}h.onclick=d.onclick=()=>{ao(b).catch(a=>{g(ep+a)})},f.appendChild(d)}if(e){const a=T(n);a.innerHTML="Owner",f.appendChild(a)}if(null!=hL&&hO){const a=T(eq);a.type=eq,
a.title="Kick user",a.className=ex,a.onclick=()=>{C(75,[af,hL,b]).then(()=>{f.remove()}).catch(a=>{g("Failed to kick this user. Message: "+a)})},f.appendChild(a)}return f}function hQ({id:a,msg:b,uid:d,vip:e,user:f,icon:h,files:i}){const j=T(l);j.setAttribute(m,a);const k=T(l);switch(k.className=cX,k.textContent=f,e){case 3:k.setAttribute(el,em);break;case 4:k.setAttribute(el,en)}{const a=T(dl);a.src=y(h),a.alt=eo,a.width=32,a.height=32,a.loading=dm,a.decoding=dn,a.draggable=!1,
null!=d&&(a.style.cursor=k.style.cursor=o,a.onclick=k.onclick=()=>{ao(d).catch(a=>{g(ep+a)})}),j.appendChild(a)}const r=T(l);if(r.appendChild(k),b.length>0){const e=T(n);if(e.textContent=b,r.appendChild(e),null!=ag&&(hO||d===ag)){{const d=T(eq);d.type=eq,d.title=er,d.className=ef,d.onclick=()=>{const f=T(l),h=T(cf);h.type=p,h.value=b,h.required=!0,h.minLength=1,h.maxLength=1e3,h.placeholder=es,h.autocomplete=et,f.appendChild(h);const i=T(eq);i.type=eq,i.title=eu,i.className=ev,f.appendChild(i)
;const j=T(eq);j.type=eq,j.title=ew,j.className=ex,f.appendChild(j),i.onclick=()=>{const c=h.value.trim();c.length<1?g(fg):c.length>1e3?g(fh):null!=af&&null!=hL?C(62,[af,a,hL,c]).then(()=>{b=c,f.remove(),d.disabled=!1}).catch(a=>{g("Failed to update message. Reason: "+a)}):g(fi)},j.onclick=()=>{f.remove(),d.disabled=!1,e.innerHTML=b},d.disabled=!0,e.innerHTML=c,e.appendChild(f)},j.appendChild(d)}{const b=T(eq);b.type=eq,b.title=eA,b.className=Z,b.onclick=()=>{null!=af&&null!=hL?(b.disabled=!0,
C(62,[af,a,hL,c]).catch(a=>{g("Failed to delete message. Reason: "+a)})):g(fi)},j.appendChild(b)}}}for(const{name:a,type:b,url:c}of i){const d=y(c);{const b=T(q);b.rel="noopener nofollow",b.href=d,b.target=dD,b.download=a,b.textContent=a||c$,r.appendChild(b)}switch(b.split(bz,2)[0]){case dX:{const a=T(dl);a.src=d,a.alt="Attachment",a.width=500,a.height=500,a.loading=dm,a.decoding=dn,a.draggable=!1,r.appendChild(a)}break;case e$:{const a=T(e$);a.src=d,a.volume=.8,a.preload="metadata",
a.controls=!0,r.appendChild(a)}break;case eR:{const a=T(eR);a.src=d,a.muted=!0,a.width=500,a.height=500,a.volume=.8,a.autoplay=!0,a.controls=!0,r.appendChild(a)}}}return j.appendChild(r),j}function hR(a,b,d,e,f=!1){const h=T(l);h.setAttribute(m,a),f&&h.setAttribute(dZ,c);{const a=T(dl);a.src="/res/group.svg",a.alt="Group",a.width=32,a.height=32,a.loading=dm,a.decoding=dn,a.draggable=!1,h.appendChild(a)}{const a=T(l);a.textContent=b,h.appendChild(a)}return h.onclick=()=>{hN||(hN=!0,
h.removeAttribute(dZ),hi.innerHTML=fj,hO=null!=ag&&e[0]===ag,C(28,[af,hL=a]).then(e=>{hM=e[e.length-1]?.id,hi.innerHTML=c;for(const a of e)hi.prepend(hQ(a));hi.scrollTo({behavior:eB,left:0,top:hi.scrollHeight});for(const a of hA)a.removeAttribute(ei);hl.setAttribute(fk,"grinfo"),hl.title="View channel info",hl.onclick=()=>{null!=as&&as();for(const a of aF)a.removeAttribute(ei);hC.setAttribute(ei,c),ad.checked=!1,W.scrollTo({top:0,left:0,behavior:eB}),hB.textContent=a,hE.textContent=b,
hF.textContent=d,hG.textContent=dg+fl+d,hD.style.display=hO?da:i,C(72,[af,a,0]).then(b=>{if(hH.innerHTML=c,b.length>0){let c=0;hH.appendChild(hP(b.shift(),!0));for(const a of b)hH.appendChild(hP(a,!1));hH.onscrollend=()=>{hH.scrollTop>=hH.scrollHeight-hH.clientHeight&&c>=0&&C(72,[af,a,c+=10]).then(a=>{a.length<10&&(c=-1);for(const b of a)hH.appendChild(hP(b,!1))})}}}).catch(a=>{g(fm+a)})},h.setAttribute(ei,c),hq.style.display=i,hk.textContent=b,hN=!1}).catch(a=>{g(fn+a),hN=!1}))},h}
function hS(a,b,d,e,f,h=!1){const j=T(l);j.setAttribute(m,a),j.setAttribute(fo,b),h&&j.setAttribute(dZ,c);{const a=T(dl);a.src=y(f),a.alt=eo,a.width=32,a.height=32,a.loading=dm,a.decoding=dn,a.draggable=!1,j.appendChild(a)}{const a=T(l);switch(a.className=cX,a.textContent=e,d){case 3:a.setAttribute(el,em);break;case 4:a.setAttribute(el,en)}j.appendChild(a)}return j.onclick=()=>{hN||(hN=!0,hO=!1,j.removeAttribute(dZ),hi.innerHTML=fj,C(28,[af,hL=a]).then(a=>{hM=a[a.length-1]?.id,hi.innerHTML=c
;for(const b of a)hi.prepend(hQ(b));hi.scrollTo({behavior:eB,left:0,top:hi.scrollHeight});for(const a of hA)a.removeAttribute(ei);hl.setAttribute(fk,"profile"),hl.title="View user profile",hl.onclick=()=>{ao(b).catch(a=>{g(ep+a)})},j.setAttribute(ei,c),hq.style.display=i,hk.textContent=e,hN=!1}).catch(a=>{g(fn+a),hN=!1}))},j}function hT(a,b){if(hL===a){const a=hi.scrollTop,c=hi.scrollHeight-hi.clientHeight;hi.appendChild(hQ(b)),a>=c-100&&hi.scrollTo({behavior:eB,left:0,top:hi.scrollHeight})}}
function hU(a,b){if(hL===a)for(const a of hj)if(a.getAttribute(m)===b){a.remove();break}}function hV(a,b,c){if(hL===a)for(const a of hj)if(a.getAttribute(m)===b){const d=a.querySelector(eN);null!=d?d.textContent=c:g("Failed to update message: "+b);break}}async function hW(a){if(hn.disabled=!0,ho.disabled=!0,hp.disabled=!0,a9.disabled=!0,hw.disabled=!0,hh.disabled=!0,hm.disabled=!0,0===hz.length)try{const a=await C(22);for(const b of a)if("#"===b[0]){const a=T(n);a.textContent=b.slice(1),
hg.appendChild(a)}else{const[a,d,e]=b.split(f,3),h=T(l);h.setAttribute(m,d),h.textContent=a,h.onclick=()=>{hN||(hN=!0,hO=!1,hi.innerHTML=fj,C(7,[hL=d]).then(b=>{hM=b[b.length-1]?.id,hi.innerHTML=c;for(const a of b)hi.prepend(hQ(a));hi.scrollTo({behavior:eB,left:0,top:hi.scrollHeight});for(const a of hz)a.removeAttribute(ei);hh.style.display="f"===e?da:i,h.setAttribute(ei,c),hk.textContent=a,hN=!1}).catch(a=>{g(fn+a),hN=!1}))},hg.appendChild(h)}}catch(a){
return void g("Failed to load channel list. Message: "+a)}if(hL=void 0,hi.innerHTML=c,hk.innerHTML="Server",hq.style.display=i,hl.setAttribute(fk,"discord"),hl.title="Open chat in Discord",hl.onclick=()=>{A("https://discord.com/api/guilds/998658232207814667/widget.json",dG).then(a=>{null!=a&&(a=JSON.parse(a).instant_invite),K(a||"https://discord.gg/djdH3kVd4v")})},hz.length>0)if(hi.onscrollend=()=>{!hN&&null!=hL&&hi.scrollTop<100&&(hN=!0,C(7,[hL,hM]).then(a=>{if(a.length>0){
const b=hi.scrollHeight;hM=a[a.length-1].id;for(const b of a)hi.prepend(hQ(b));hi.scrollTo({behavior:eB,left:0,top:hi.scrollHeight-b})}}).catch(a=>{g(fp+a)}).finally(()=>{hN=!1}))},hm.onkeydown=a=>{if(a.key===cj){if(a.preventDefault(),a.stopPropagation(),null==af)return void a8.click();const b=hm.value.trim();if(b.length<1)return void g(fg);if(b.length>1e3)return void g(fh);if(null==hL)return void g("Please select a valid channel for posting messages.");hm.value=c,hm.disabled=!0,
C(8,[af,hL,b]).then(()=>{hm.disabled=!1}).catch(a=>{g("Failed to post text message. Message: "+a),hm.disabled=!1})}},az=hT,aA=hU,aC=hV,null!=a){for(const b of hz)if(b.getAttribute(m)===a){b.click();break}}else hg.querySelector(l).click();else hg.innerHTML="No public channels are available at this moment.",hm.onkeydown=hi.onscrollend=az=aA=aC=null;hm.onfocus=a=>{a.preventDefault(),a.stopPropagation(),null==af&&a8.click()},ho.removeAttribute(ei),hp.removeAttribute(ei),hn.setAttribute(ei,c),
he.removeAttribute(cs),hf.removeAttribute(cs),hg.style.display=da,hn.disabled=!1,ho.disabled=!1,hp.disabled=!1,a9.disabled=!1,hw.disabled=!1,hh.disabled=!1,hm.disabled=!1}async function hX(){if(null!=af&&null!=ag){hn.disabled=!0,ho.disabled=!0,hp.disabled=!0,a9.disabled=!0,hw.disabled=!0,hh.disabled=!0,hm.disabled=!0,hL=void 0,he.innerHTML=c,hi.innerHTML=c,hk.innerHTML="Messages",hq.style.display=da,hl.removeAttribute(fk);try{
for(const{id:a,name:b,mode:c,code:d,users:e,unread:f}of await C(27,af))if(c===b6){const{id:b,uid:c,vip:d,icon:g}=await C(1,e[0]);he.appendChild(hS(a,c,d,b,g,f))}else he.appendChild(hR(a,b,d,e,f))}catch(a){return void g("Failed to load friends list. Message: "+a)}az=hT,aA=hU,aC=hV,hi.onscrollend=()=>{!hN&&null!=hL&&hi.scrollTop<100&&(hN=!0,C(28,[af,hL,hM]).then(a=>{if(a.length>0){const b=hi.scrollHeight;hM=a[a.length-1].id;for(const b of a)hi.prepend(hQ(b));hi.scrollTo({behavior:eB,left:0,
top:hi.scrollHeight-b})}}).catch(a=>{g(fp+a)}).finally(()=>{hN=!1}))},hm.onkeydown=a=>{if(a.key===cj){a.preventDefault(),a.stopPropagation();const b=hm.value.trim();if(b.length<1)return void g(fg);if(b.length>1e3)return void g(fh);if(null==hL)return void g("Please select a valid channel before posting messages.");hm.value=c,hm.disabled=!0,(async()=>{if(hL.startsWith(fq)){const a=hL.slice(4);try{const b=hS(hL=await C(69,[af,a]),a,hK,hJ||c,hI||f0);b.setAttribute(ei,c),he.appendChild(b)}catch(a){
return void g("Failed to create new channel. Message: "+a)}hi.innerHTML=c}try{await C(8,[af,hL,b])}catch(a){g("Failed to post text message. Reason: "+a)}})().then(()=>{hm.disabled=!1})}},hn.removeAttribute(ei),hp.removeAttribute(ei),ho.setAttribute(ei,cv),hf.removeAttribute(cs),hg.removeAttribute(cs),he.style.display=da,hh.style.display=da,hn.disabled=!1,ho.disabled=!1,hp.disabled=!1,a9.disabled=!1,hw.disabled=!1,hh.disabled=!1,hm.disabled=!1}else a8.click()}{
const hY=b("gr-name"),hZ=b("gr-code"),h$=b("gr-join"),h_=b("gr-create");hY.onblur=()=>{const a=hY.value.trim();a.length>0&&(hY.value=a)},hZ.onblur=()=>{const a=hZ.value.trim();a.length>0&&(hZ.value=a)},h$.onclick=()=>{const a=hZ.value.trim();12===a.length?(h$.disabled=!0,C(70,[af,a]).then(({id:b,name:d,users:e})=>{{const f=hR(hL=b,d,a,e);f.setAttribute(ei,c),he.appendChild(f),f.click()}hq.style.display=i}).catch(a=>{g(fr+a)}).finally(()=>{h$.disabled=!1
})):g("The invite code must have exactly 12 characters.")},h_.onclick=()=>{const a=hY.value.trim();a.length<2?g(fs):a.length>30?g(ft):a.indexOf(bH,0)>=0||a.indexOf(bI,0)>=0?g(fu):(h_.disabled=!0,C(68,[af,a]).then(({id:a,name:b,code:d,users:e})=>{{const f=hR(hL=a,b,d,e);f.setAttribute(ei,c),he.appendChild(f),f.click()}hq.style.display=i}).catch(a=>{g("Failed to create new group. Message: "+a)}).finally(()=>{h_.disabled=!1}))}}{const i0=T(cf);i0.type=c$,i0.multiple=!0,i0.onchange=async()=>{
if(null==hL)return void g("Please select a valid channel before uploading files.");const a=i0.files;if(null!=a&&a.length>0){if(a.length>10)return void g("Uploading more than 10 files at once is not supported.");hh.disabled=!0,hm.disabled=!0;try{const b=[];let c=0;for(const d of a){const a=d.size;if(a<1)throw new mv("Empty files are not allowed.");if(a>1e7)throw new mv("Files larger than 10MB are not supported.");if((c+=a)>12e6)throw new mv("The total size of a single upload cannot exceed 12MB.")
;b.push({name:d.name,attachment:await d.arrayBuffer()})}await C(12,[af,hL,b])}catch(a){g("Failed to upload file. Message: "+a)}i0.value=c,hh.disabled=!1,hm.disabled=!1}},hh.onclick=()=>{i0.click()}}b("grleave").onclick=()=>{null!=hL&&hL[0]===fv?C(71,[af,hL]).then(()=>{null!=as&&as();for(const a of aF)a.removeAttribute(ei);ad.checked=!1,hy.setAttribute(ei,c),a9.setAttribute(ei,c),W.scrollTo({top:0,left:0,behavior:eB}),hX()}).catch(a=>{g("Failed to leave the group. Message: "+a)}):g(fw)},
hD.onclick=()=>{const a=T(l),b=T(cf);b.type=p,b.value=hE.innerHTML,b.required=!0,b.minLength=2,b.maxLength=30,b.placeholder="Group Name",b.autocomplete=et,a.appendChild(b);const c=T(eq);c.type=eq,c.title=eu,c.className=ev,a.appendChild(c);const d=T(eq);d.type=eq,d.title=ew,d.className=ex,a.appendChild(d),b.onblur=()=>{const a=b.value.trim();a.length>0&&(b.value=a)},c.onclick=()=>{if(null==hL||hL[0]!==fv||!hO)return void g(fw);const c=b.value.trim()
;c.length<2?g(fs):c.length>30?g(ft):c.indexOf(bH,0)>=0||c.indexOf(bI,0)>=0?g(fu):C(74,[af,hL,c]).then(()=>{a.replaceWith(hD),hE.textContent=c}).catch(a=>{g("Failed to update group name. Message: "+a)})},d.onclick=()=>{a.replaceWith(hD)},hD.replaceWith(a),b.select()},a9.onclick=hw.onclick=()=>{null!=as&&as();for(const a of aF)a.removeAttribute(ei);ad.checked=!1,hy.setAttribute(ei,c),a9.setAttribute(ei,c),W.scrollTo({top:0,left:0,behavior:eB}),null==hL&&hW(),a1||(ai||(ms.title="NettleWeb Chat"),
as=I,P.replaceState(void 0,c,fx))},ho.onclick=()=>{hX()},hn.onclick=()=>{hW()},am=async({id:a,uid:b,vip:d,icon:e})=>{await hX(),hq.style.display=i,null!=as&&as();for(const a of aF)a.removeAttribute(ei);ad.checked=!1,hy.setAttribute(ei,c),a9.setAttribute(ei,c),W.scrollTo({top:0,left:0,behavior:eB});for(const a of hA)if(a.getAttribute(fo)===b)return void a.click();hL=fq+b,hK=d||void 0,hI=e,hk.innerHTML=hJ=a,hi.innerHTML="<div>Send a message to start a new chat with "+a+".</div>"
;for(const a of hA)a.removeAttribute(ei)},ap=async a=>{if(a[0]===fv){await hX(),hq.style.display=i;for(const b of hA)if(b.getAttribute(m)===a){b.click();break}}else await hW(a);null!=as&&as();for(const a of aF)a.removeAttribute(ei);ad.checked=!1,hy.setAttribute(ei,c),a9.setAttribute(ei,c),W.scrollTo({top:0,left:0,behavior:eB})}}{const i1=hf.children;let i2=null;const i3=JSON.parse(a5.getItem(fy)||"[]");function i4({role:a,text:b}){const c=T(l);{const b=T(dl);b.width=32,b.height=32,b.loading=dm,
b.decoding=dn,b.draggable=!1,"u"===a?(b.src="res/user.svg",b.alt="User"):(b.src="res/bot.svg",b.alt="Assistant"),c.appendChild(b)}{const a=T(l);a.textContent=b,c.appendChild(a)}return hi.appendChild(c),c}function i5(a){const b=a.title;if(typeof b!==s)throw new mv("Invalid chat object");const d=T(l);d.onclick=()=>{for(const a of i1)a.removeAttribute(ei);d.setAttribute(ei,cv),hi.innerHTML=c,hk.textContent=b;for(const b of i2=a.msgs)i4(b);hi.scrollTo({behavior:eB,left:0,top:hi.scrollHeight})};{
const a=T(l);a.textContent=b,d.appendChild(a)}{const b=T(eq);b.type=eq,b.title=eA,b.onclick=b=>{b.preventDefault(),b.stopPropagation();const e=i3.indexOf(a,0);e>=0&&(i2=null,d.remove(),i3.splice(e,1),hi.innerHTML=c,a5.setItem(fy,JSON.stringify(i3,void 0,0)))},d.appendChild(b)}return hf.insertBefore(d,i1[1]),d}b("newchat").onclick=()=>{for(const a of i1)a.removeAttribute(ei);i2=null,hi.innerHTML=c,hk.innerHTML=fz},hp.onclick=()=>{for(const a of i1)a.removeAttribute(ei);if(i2=null,hi.innerHTML=c,
hk.innerHTML=fz,hq.style.display=i,hl.removeAttribute(fk),hm.onfocus=hi.onscrollend=az=aA=aC=null,i1.length<2)for(const a of i3)i5(a);hm.onkeydown=a=>{if(a.key===cj){a.preventDefault(),a.stopPropagation();const b=hm.value.trim();if(b.length<1)return void g(fg);if(b.length>8e3)return void g("Messages cannot be longer than 8000 characters.");if(hm.value=c,hm.disabled=!0,null==i2){const a={title:b.slice(0,100),msgs:i2=[]};i3.push(a),i5(a).setAttribute(ei,cv)}const d={role:"u",text:b};i4(d),
i2.push(d);const e={role:q,text:f9},f=i4(e),h=f.lastElementChild;av=a=>{if(a.length>0){const b=hi.scrollTop,c=hi.scrollHeight-hi.clientHeight;h.textContent=e.text=a,b>=c-100&&hi.scrollTo({behavior:eB,left:0,top:hi.scrollHeight})}else i2.push(e),hm.disabled=!1,av=aw=null,a5.setItem(fy,JSON.stringify(i3,void 0,0))},aw=a=>{i2.pop(),f.remove(),hm.disabled=!1,av=aw=null,g("Failed to process the request. Message: "+a)},ah.send(mE.encode("\x02"+JSON.stringify(i2,void 0,0)),{compress:!0})}},
hn.removeAttribute(ei),ho.removeAttribute(ei),hp.setAttribute(ei,cv),he.removeAttribute(cs),hg.removeAttribute(cs),hf.style.display=da,hh.style.display=i,hn.disabled=!1,ho.disabled=!1,hp.disabled=!1,hh.disabled=!0,hm.disabled=!1}}b(bP).onclick=()=>{if(hd.style.display!==da){if(null==hd.firstElementChild){const a=new o6({locale:db,emojiVersion:1e3});a.addEventListener(cl,a=>{a.preventDefault(),a.stopPropagation();const b=a.detail.unicode
;null!=b&&hm.setRangeText(b,hm.selectionStart||0,hm.selectionEnd||0,"end")}),hd.appendChild(a)}hd.style.display=da}else hd.style.display=i}}{const i6=b("nwidget"),i7=b("nclear"),i8=b("notif");ac.onclick=()=>{if(null!=af){if(i6.hasAttribute(ei))return i6.removeAttribute(ei),void ac.removeAttribute(ei);ac.disabled=!0,i8.innerHTML=c,C(60,af).then(a=>{if(a.length>0){for(const b of a){const a=T(l);{const c=T(l);switch(b.type){case 0:c.textContent=b.text;break;case 1:
c.innerHTML=fA+b.user+"</b> sent a direct message to you.",a.onclick=()=>{C(1,b.fuid).then(a=>{am(a).catch(a=>{g(fB+a)})}).catch(a=>{g("Failed to load user info. Message: "+a)})};break;case 2:c.innerHTML=fA+b.user+"</b> mentioned you in a chat channel.",a.onclick=()=>{ap(b.chId).catch(a=>{g(fB+a)})};break;case 3:c.innerHTML=fA+b.user+"</b> mentioned you in a game comment.",a.onclick=()=>{aq().then(()=>{const a=b.game;for(const b of aj)if(b.date===a){an(b).catch(a=>{g(dk+a)});break}}).catch(a=>{
g("Failed to get game information. Message: "+a)})};break;case 4:c.innerHTML=fA+b.user+"</b> requested to be friend with you.",a.onclick=()=>{a8.click()};break;default:c.innerHTML="Error: Failed to parse message."}a.appendChild(c)}{const c=T(n);c.textContent=z(b.date),a.appendChild(c)}i8.appendChild(a)}i7.disabled=!1,ac.removeAttribute(dZ)}else i7.disabled=!0,i8.innerHTML="<div>You don't have any notifications yet.</div>"}).catch(a=>{g("Failed to fetch notifications. Message: "+a)
}).finally(()=>{ac.disabled=!1,i6.setAttribute(ei,c),ac.setAttribute(ei,c)})}else a8.click()},i7.onclick=()=>{i7.disabled=!0,C(81,af).then(()=>{i8.innerHTML="<div>Notifications cleared!</div>"}).catch(a=>{g("Failed to clear notifications. Message: "+a)}).finally(()=>{i7.disabled=!1})}}{const i9=b(m),ia=b("bio"),ib=b("af"),ic=b("dm"),id=b("pf-games"),ie=b("avatar"),ig=b("profile-page");ao=async a=>{const b=await C(1,a);null!=as&&as();for(const a of aF)a.removeAttribute(ei);W.scrollTo({top:0,
left:0,behavior:eB}),ad.checked=!1,ig.setAttribute(ei,cv),ib.disabled=!1,ib.innerHTML="Add Friend",ie.src=y(b.icon),ia.textContent=b.bio||fC,id.innerHTML=c,id.onscrollend=null,id.removeAttribute(cs);{const a=i9.textContent=b.id;a1||(as=I,P.replaceState(void 0,c,"/@"+a))}switch(b.vip){case 3:i9.setAttribute(el,em);break;case 4:i9.setAttribute(el,en);break;default:i9.removeAttribute(el)}ib.onclick=()=>{null!=af?C(24,[af,a]).then(()=>{ib.disabled=!0,ib.innerHTML=fD}).catch(a=>{g(fE+a)}):a8.click()
},ic.onclick=()=>{null!=af?am(b).catch(a=>{g(fB+a)}):a8.click()},await aq();{const b=aj.filter(b=>b.user===a);if(b.length>0){let a=25;for(const a of b.slice(0,25))id.appendChild(G(a));id.onscrollend=()=>{if(id.scrollTop>=id.scrollHeight-id.clientHeight){const c=a+25;c>=b.length&&(id.onscrollend=null);for(const d of b.slice(a,a=c))id.appendChild(G(d))}}}else id.style.overflow="unset",id.innerHTML="This user has not uploaded any games yet."}}}
const aE=b("chat-profile"),aF=ms.querySelectorAll("header>nav>ul>li>button, #content>div, #nmsg-btn, #accn-btn, #nwidget");{const ih=b("ff"),ii=b("accountinfo-page"),ij=b("ac-friends");function ik(a,b){const d=b.uid;if(typeof d!==s)throw new mv("Internal Error");const e=T(dl);e.src=y(b.icon),e.alt=eo,e.width=48,e.height=48,e.loading=dm,e.decoding=dn,e.draggable=!1,a.appendChild(e);{const c=T(l);switch(c.className=cX,c.textContent=b.id,b.vip){case 3:c.setAttribute(el,em);break;case 4:
c.setAttribute(el,en)}e.onclick=c.onclick=()=>{ao(d).catch(a=>{g(ep+a)})},a.appendChild(c)}switch(b.state){case 1:{const b=T(eq);b.type=eq,b.title="Cancel request",b.className=ex,b.onclick=()=>{C(25,[af,d]).then(()=>{a.remove()}).catch(a=>{g("Failed to cancel friend request. Message: "+a)})},a.appendChild(b)}{const b=T(n);b.innerHTML=fD,a.appendChild(b)}break;case 2:{const e=T(eq);e.type=eq,e.title=cT,e.className=ev,e.onclick=()=>{C(24,[af,d]).then(()=>{b.state=0,a.innerHTML=c,ik(a,b)
}).catch(a=>{g("Failed to accept friend request. Message: "+a)})},a.appendChild(e)}{const b=T(eq);b.type=eq,b.title="Reject",b.className=ex,b.onclick=()=>{C(25,[af,d]).then(()=>{a.remove()}).catch(a=>{g("Failed to reject friend request. Message: "+a)})},a.appendChild(b)}{const b=T(n);b.innerHTML="Accept friend request?",a.appendChild(b)}break;default:{const b=T(eq);b.type=eq,b.title="Remove friend",b.className=ex,b.onclick=()=>{C(25,[af,d]).then(()=>{a.remove()}).catch(a=>{
g("Failed to remove friend. Message: "+a)})},a.appendChild(b)}{const c=T(eq);c.type=eq,c.title=es,c.className=cy,c.onclick=()=>{am(b).catch(a=>{g(fB+a)})},a.appendChild(c)}}}al=()=>{C(26,[af,0]).then(a=>{if(ij.innerHTML=c,Array.isArray(a)&&a.length>0){let b=0;for(const b of a){const a=T(l);ik(a,b),ij.appendChild(a)}ij.onscrollend=()=>{ij.scrollTop>=ij.scrollHeight-ij.clientHeight&&b>=0&&C(26,[af,b+=10]).then(a=>{a.length<10&&(b=-1);for(const b of a){const a=T(l);ik(a,b),ij.appendChild(a)}})}}
}).catch(a=>{g(fm+a)})},b(fF).onclick=aE.onclick=a8.onclick=()=>{null!=as&&as();for(const a of aF)a.removeAttribute(ei);ij.innerHTML="Loading...",W.scrollTo({top:0,left:0,behavior:eB}),a8.setAttribute(ei,cv),ii.setAttribute(ei,cv),ad.checked=!1,typeof af===s&&al()},ih.onclick=()=>{const a=T(l),b=T(cf);b.type=p,b.minLength=2,b.maxLength=30,b.spellcheck=!1,b.placeholder=fG,b.autocomplete=et,a.appendChild(b);const c=T(eq);c.type=eq,c.title="Add",c.className=ev,a.appendChild(c);const d=T(eq)
;d.type=eq,d.title=ew,d.className=ex,a.appendChild(d),b.onblur=()=>{const a=b.value.trim().toLowerCase();a.length>0&&(b.value=a)},c.onclick=()=>{const c=b.value.trim().toLowerCase();c.length<4||c.length>20||!/^[\-a-z0-9]+$/.test(c)?g(fe):C(1,ff+c).then(b=>{C(24,[af,b.uid]).then(()=>{const c=T(l);b.state=1,ik(c,b),ij.appendChild(c),a.replaceWith(ih)}).catch(a=>{g(fE+a)})}).catch(a=>{g("Failed to retrieve user information. Message: "+a)})},d.onclick=()=>{a.replaceWith(ih)},ih.replaceWith(a)}}{
const il=b("home-btn"),im=b("apps-btn"),io=b("info-btn"),ip=b("home-page"),iq=b("gamemu-page"),ir=b("desmos-page"),is=b("webemu-page"),it=b("console-page"),iu=b("unbl0ck-page"),iv=b("services-page"),iw=b("mirrorlink-page"),ix=b("uploadgames-page"),iy=b("settings-page"),iz=O.pathname,iA=new URLSearchParams(O.search);switch(b("logo").onclick=il.onclick=()=>{null!=as&&as();for(const a of aF)a.removeAttribute(ei);ad.checked=!1,ip.setAttribute(ei,c),il.setAttribute(ei,c),W.scrollTo({top:0,left:0,
behavior:eB})},b("goto-apps").onclick=im.onclick=()=>{null!=as&&as();for(const a of aF)a.removeAttribute(ei);W.scrollTo({top:0,left:0,behavior:eB}),ad.checked=!1,im.setAttribute(ei,c),iv.setAttribute(ei,c),a1||(ai||(ms.title="NettleWeb Apps"),as=I,P.replaceState(void 0,c,fH))},io.onclick=()=>{null!=as&&as();for(const a of aF)a.removeAttribute(ei);W.scrollTo({top:0,left:0,behavior:eB}),ad.checked=!1,io.setAttribute(ei,c),iw.setAttribute(ei,c),a1||(ai||(ms.title="About NettleWeb"),as=I,
P.replaceState(void 0,c,fI))},b("u").onclick=()=>{null!=as&&as();for(const a of aF)a.removeAttribute(ei);iu.setAttribute(ei,c),ad.checked=!1,W.scrollTo({top:0,left:0,behavior:eB})},b(dU).onclick=()=>{null!=as&&as();for(const a of aF)a.removeAttribute(ei);iq.setAttribute(ei,c),ad.checked=!1,W.scrollTo({top:0,left:0,behavior:eB})},b(dS).onclick=()=>{null!=as&&as();for(const a of aF)a.removeAttribute(ei);is.setAttribute(ei,c),ad.checked=!1,W.scrollTo({top:0,left:0,behavior:eB})},
b("c").onclick=()=>{null!=as&&as();for(const a of aF)a.removeAttribute(ei);it.setAttribute(ei,c),ad.checked=!1,W.scrollTo({top:0,left:0,behavior:eB})},b(t).onclick=()=>{null!=as&&as();for(const a of aF)a.removeAttribute(ei);ir.setAttribute(ei,c),ad.checked=!1,W.scrollTo({top:0,left:0,behavior:eB})},b("ug").onclick=()=>{null!=as&&as();for(const a of aF)a.removeAttribute(ei);ix.setAttribute(ei,c),ad.checked=!1,W.scrollTo({top:0,left:0,behavior:eB})},b("settings").onclick=()=>{
const a=iy.hasAttribute(ei);null!=as&&as();for(const a of aF)a.removeAttribute(ei);a?(il.setAttribute(ei,cv),ip.setAttribute(ei,cv)):iy.setAttribute(ei,cv),ad.checked=!1,W.scrollTo({top:0,left:0,behavior:eB})},P.scrollRestoration="manual",P.replaceState(void 0,c,bz),iz){case bz:break;case fH:im.click();break;case fx:a9.click();break;case eQ:aa.click();break;case f4:ab.click();break;case fI:io.click();break;default:if("/@"===iz.slice(0,2)){const iB=iz.slice(1);if(iB.length<=50)try{await ao(iB)
}catch(iC){g(ep+iC)}}else if(iz.slice(0,6)===fl){const iD=iz.slice(6);if(12===iD.length)try{const iE=await C(73,iD);b("igrcode").textContent=iD,b("igrname").textContent=iE.name,b("gr-users").textContent=iE.users,b("gr-accept").onclick=()=>{null!=af?C(70,[af,iD]).then(({id:a})=>{ap(a).catch(a=>{g(fB+a)})}).catch(a=>{g(fr+a)}):a8.click()};for(const iF of aF)iF.removeAttribute(ei);b("group-invite-page").setAttribute(ei,c),ad.checked=!1,W.scrollTo({top:0,left:0,behavior:eB})}catch(iG){
g("Failed to open invite link. Message: "+iG)}}else if("/reset/"===iz.slice(0,7)){const iH=iz.slice(7);if(256===iH.length){const iI=b("account-reset-page");for(const iL of aF)iL.removeAttribute(ei);iI.setAttribute(ei,c),ad.checked=!1,W.scrollTo({top:0,left:0,behavior:eB});const iJ=b("np"),iK=b("rp");b("reset").onclick=()=>{const a=iJ.value;a.length<8||a.length>30?g(fJ):a===iK.value?C(76,[iH,a]).then(()=>{iI.remove(),a8.click()}).catch(a=>{g("Failed to reset password. Message: "+a)}):g(fK)}}
}else if(iz.length>4&&iz.length<20){const iM=parseInt(iz.slice(1),36);if(Number.isSafeInteger(iM)&&iM>0){await aq();for(const iN of aj){const iO=iN.date;if(iO===iM){if(iA.get("hidegui")===cv)return Y.innerHTML=c,Y.appendChild(F(iN.type,E(iN.file,iO.toString(36)))),void M();try{await an(iN)}catch(iP){g(dk+iP)}break}}}}else g("Error: Page does not exist: "+iz)}iA.get(fv)===cv&&setTimeout(()=>{W.scrollTo({top:W.scrollHeight,left:0,behavior:eB})},5e3),b(r).remove(),W.setAttribute(e3,c)}{
const iQ=b("headlines");await aq();try{const iR=await C(47);if(iR.length<1)return void(iQ.innerHTML="No articles are available at this moment.");iQ.innerHTML=c;for(const iS of iR){const iT=T(l),iU=iS.urlToImage||null;{const iV=T(dl);iV.src=null==iU?eT:y(iU),iV.alt=eS,iV.width=160,iV.height=90,iV.loading=dm,iV.decoding=dn,iV.draggable=!1,iT.appendChild(iV)}{const iW=T(l);{const iX=T(l);iX.className=eU,iX.textContent=iS.title,iW.appendChild(iX)}{const iY=T(l);iY.className=eg,
iY.textContent=iS.description||"Description is not available for this article.",iW.appendChild(iY)}{const iZ=T(l);iZ.className=eZ,iZ.textContent="Source: "+(iS.source.name||fL)+"; Author: "+(iS.author||fL)+"; Published at "+z(iS.publishedAt),iW.appendChild(iZ)}iT.appendChild(iW)}iT.onclick=()=>{K(iS.url)},iQ.appendChild(iT)}}catch(i$){iQ.textContent="Failed to fetch from the API server. Message: "+i$}}Q===dg?ae=ha(gr({appId:"1:176227430389:web:94270de43b7eb971c03abc",
apiKey:"AIzaSyCPXTy7dt3fpcLd8kVTBtXy0xuBdeuhbFc",projectId:"whitespider",authDomain:"whitespider.firebaseapp.com",databaseURL:"https://whitespider-default-rtdb.firebaseio.com",storageBucket:"whitespider.firebasestorage.app",measurementId:"G-F72WBJT57S",messagingSenderId:"176227430389"},bB)):M();{async function i_(){al(),a8.title="My Account",a8.setAttribute("data-ac",c),b("ac-prof").style.display=da,b(fF).remove(),b(fM).remove()
;const a=b("ac-bio"),d=b("ac-name"),e=b("ac-email"),f=b("ac-un"),h=b("ac-edit"),j=b("ac-link"),k=b("ac-bio-edit"),m=b("ac-name-edit"),o=b("ac-email-edit"),q=b("cp"),r=b("rs"),t=b("tf");a5.getItem(fN)===cv&&(t.setAttribute(fO,c),t.textContent=fP);const u=b("ch-avatar"),v=u.firstElementChild,w=T(dl);w.alt=eo,w.width=40,w.height=40,w.loading=dd,w.decoding=de,w.draggable=!1,aE.appendChild(w);const x=T(l);x.className=cX,aE.appendChild(x),aE.style.display=da;const z=await C(2,af);ar=z.likes
;const A=z.id,D=z.uid,E=z.name;if(null!=ae&&(hb(ae,D,{global:!0}),hc(ae,{id:A,uid:D,name:E},{global:!1})),typeof A!==s||A.length<4||typeof D!==s||D.length<2)g("Error: Server response parse error.");else{switch(a.textContent=z.bio||fC,d.textContent=E||fQ,e.textContent=z.email||fQ,v.src=w.src=y(z.icon),f.textContent=A,x.textContent=A,b("ac-uid").textContent=D,z.unread&&ac.setAttribute(dZ,c),z.vip){case 3:b(fR).textContent="Gold \u{1f451}",f.setAttribute(el,em),x.setAttribute(el,em);break;case 4:
b(fR).textContent="Diamond \u{1f48e}",f.setAttribute(el,en),x.setAttribute(el,en);break;default:b(fR).textContent=eE}{const a=b("ac-games"),c=aj.filter(a=>a.user===D);let d=25;for(const b of c.slice(0,25))a.appendChild(G(b));a.onscrollend=()=>{if(d<c.length&&a.scrollTop>=a.scrollHeight-a.clientHeight)for(const b of c.slice(d,d+=25))a.appendChild(G(b))}}u.onclick=()=>{const a=T(cf);a.type=c$,a.accept="image/*",a.onchange=async()=>{const b=a.files?.item(0);if(null!=b){const a=await B(b,512,512)
;if(null==a)return void g("Error: Failed to resize image.");try{await C(4,[af,await a.arrayBuffer()])}catch(a){return void g("Failed to upload the image file. Message: "+a)}const c=URL.createObjectURL(a);v.src=w.src=c,await v.decode(),await w.decode(),URL.revokeObjectURL(c)}},a.click()},h.onclick=()=>{const a=T(l),b=T(cf);b.type=p,b.value=f.innerHTML,b.minLength=4,b.maxLength=20,b.spellcheck=!1,b.placeholder=fG,b.autocomplete=et,a.appendChild(b);const c=T(eq);c.type=eq,c.title=eu,c.className=ev,
a.appendChild(c);const d=T(eq);d.type=eq,d.title=ew,d.className=ex,a.appendChild(d),b.onblur=()=>{const a=b.value.trim().toLowerCase();a.length>0&&(b.value=a)},c.onclick=()=>{const c=b.value.trim().toLowerCase();c.length<4||c.length>20?g(fS):/^[\-a-z0-9]+$/.test(c)?C(3,[af,c]).then(()=>{a.replaceWith(f),f.textContent=c,x.textContent=c,h.removeAttribute(cs)}).catch(a=>{g("Failed to change username. Message: "+a)}):g("Username must contain only hyphens, 0-9, lowercase a-z")},d.onclick=()=>{
a.replaceWith(f),h.removeAttribute(cs)},h.style.display=i,f.replaceWith(a),b.select()},j.onclick=()=>{const a=di+ff+A,b=T(n);b.textContent=a,j.replaceWith(b),navigator.clipboard.writeText(a).catch(a=>{g(eG+(a+""))})},k.onclick=()=>{const b=T(l),c=T(cf);c.type=p,c.value=a.innerHTML,c.minLength=1,c.maxLength=500,c.placeholder="Bio",c.autocomplete=et,b.appendChild(c);const d=T(eq);d.type=eq,d.title=eu,d.className=ev,b.appendChild(d);const e=T(eq);e.type=eq,e.title=ew,e.className=ex,
b.appendChild(e),c.onblur=()=>{const a=c.value.trim();a.length>0&&(c.value=a)},d.onclick=()=>{const d=c.value.trim();d.length>500?g("Bio cannot have more than 500 characters in length."):C(55,[af,d]).then(()=>{b.replaceWith(a),k.removeAttribute(cs),a.textContent=d||fC}).catch(a=>{g("Failed to update bio. Message: "+a)})},e.onclick=()=>{b.replaceWith(a),k.removeAttribute(cs)},k.style.display=i,a.replaceWith(b),c.select()},m.onclick=()=>{const a=T(l),b=T(cf);b.type=p,b.value=d.innerHTML,
b.minLength=2,b.maxLength=30,b.spellcheck=!1,b.placeholder="Name",b.autocomplete=et,a.appendChild(b);const c=T(eq);c.type=eq,c.title=eu,c.className=ev,a.appendChild(c);const e=T(eq);e.type=eq,e.title=ew,e.className=ex,a.appendChild(e),b.onblur=()=>{const a=b.value.trim();a.length>0&&(b.value=a)},c.onclick=()=>{const c=b.value.trim();c.length>30?g("Name cannot have more than 30 characters in length."):C(20,[af,c]).then(()=>{a.replaceWith(d),d.textContent=c,m.removeAttribute(cs)}).catch(a=>{
g("Failed to update name. Message: "+a)})},e.onclick=()=>{a.replaceWith(d),m.removeAttribute(cs)},m.style.display=i,d.replaceWith(a),b.select()},o.onclick=()=>{const a=T(l),b=T(cf);b.type=fT,b.value=e.innerHTML,b.minLength=6,b.maxLength=320,b.spellcheck=!1,b.placeholder=fU,b.autocomplete=et,a.appendChild(b);const d=T(eq);d.type=eq,d.title=eu,d.className=ev,a.appendChild(d);const f=T(eq);f.type=eq,f.title=ew,f.className=ex,a.appendChild(f),b.onblur=()=>{const a=b.value.trim().toLowerCase()
;a.length>0&&(b.value=a)},d.onclick=()=>{const f=b.value.trim().toLowerCase();f.length<6||f.length>320||f.indexOf(ff,1)<0?g("Please provide a valid email address."):C(19,[af,f]).then(()=>{{const b=T(l);b.textContent=fV,a.prepend(b)}b.type=p,b.value=c,b.minLength=6,b.maxLength=6,b.placeholder=fW,b.onblur=()=>{const a=b.value.trim();a.length>0&&(b.value=a)},d.onclick=()=>{const c=b.value.trim();6===c.length&&/^\d+$/.test(c)?C(18,[af,c]).then(()=>{a.replaceWith(e),e.textContent=f,
o.removeAttribute(cs)}).catch(a=>{g("Failed to verify your email. Message: "+a)}):g(fX)}}).catch(a=>{g("Failed to update your email address. Message: "+a)})},f.onclick=()=>{a.replaceWith(e),o.removeAttribute(cs)},o.style.display=i,e.replaceWith(a),b.select()},q.onclick=()=>{const a=T(l);{const b=T(l);b.setAttribute(cs,"position:relative;display:block;width:fit-content;height:fit-content;margin:10px 0px;padding:5px;line-height:18px;"),
b.innerHTML="Notice: If your account was created with your Google account and does not have a password, set the current password field to 'CHANGEME!'. After changing your password, previously logged-in sessions will still have access to your account. To revoke the access, click the 'logout all sessions' button down below.",a.appendChild(b)}const b=T(cf);b.type=cY,b.minLength=8,b.maxLength=30,b.spellcheck=!1,b.placeholder="Current password",b.autocomplete=et,a.appendChild(b);const c=T(cf)
;c.type=cY,c.minLength=8,c.maxLength=30,c.spellcheck=!1,c.placeholder="New password",c.autocomplete=et,a.appendChild(c);const d=T(cf);d.type=cY,d.minLength=8,d.maxLength=30,d.spellcheck=!1,d.placeholder=fY,d.autocomplete=et,a.appendChild(d);const e=T(eq);e.type=eq,e.title=fZ,e.className=ev,a.appendChild(e);const f=T(eq);f.type=eq,f.title=ew,f.className=ex,a.appendChild(f),e.onclick=()=>{const e=b.value;if(e.length<8||e.length>30)return void g("The current password must have 8 to 30 characters.")
;const f=c.value;f.length<8||f.length>30?g(fJ):e!==f?f===d.value?C(9,[af,e,f]).then(()=>{a.replaceWith(q)}).catch(a=>{g("Failed to change password. Message: "+a)}):g(fK):g("The new password must be different from the current password.")},f.onclick=()=>{a.replaceWith(q)},q.replaceWith(a)},r.onclick=()=>{C(43,af).then(a=>{typeof a===s&&2048===a.length?(ah.send(mE.encode(d$+(af=a))),a5.setItem(dK,a),r.disabled=!0):g("Error: Remote returned invalid token.")}).catch(a=>{
g("Failed to revoke login tokens. Message: "+a)})},t.onclick=()=>{const a=T(l);if(t.hasAttribute(fO)){const b=T(cf);b.type=p,b.minLength=6,b.maxLength=6,b.spellcheck=!1,b.placeholder=fW,b.autocomplete=et,a.appendChild(b);const c=T(eq);c.type=eq,c.title=fZ,c.className=ev,a.appendChild(c),c.onclick=()=>{const c=b.value.trim();6===c.length&&/^\d+$/.test(c)?C(46,[af,c]).then(()=>{a5.setItem(fN,b6),a.replaceWith(t),t.removeAttribute(fO),t.textContent="Enable Two-Factor"}).catch(a=>{g(f$+a)}):g(fX)}
}else{{const b=T(l);b.setAttribute(cs,"position:relative;display:block;width:fit-content;height:fit-content;margin:15px 0px;line-height:18px;white-space:pre-wrap;"),
b.innerHTML='In order to enable two-factor authentication (2FA), please follow the steps below:\n1. Install an <a href="https://play.google.com/store/apps/details?id=com.google.android.apps.authenticator2" target="_blank" rel="noopener">authenticator app</a> if you don\'t have one already.\n2. Scan the QR code below or manually input the secret to save your account onto the authenticator.\n3. Input the 6-digit verification code generated below to verify.\n\nAfter enabling 2FA, you will be required to input the generated 6-digit verification code everytime as you login for enhanced account security.\n\nTo avoid being locked out, save the secret or a screenshot of the QR code across multiple devices, so that it could be restored back into the authenticator in case you lost your data.',
a.appendChild(b)}const b=mF.encode(crypto.getRandomValues(new my(new mz(32),0,32)));{const c=T(dl);c.alt="QR Code",c.width=147,c.height=147,c.loading=dd,c.decoding=de,c.draggable=!1,c.src=nl("otpauth://totp/NettleWeb:"+A+"?secret="+b+"&issuer=NettleWeb&algorithm=SHA1").toDataURL({type:bO,scale:3}),a.appendChild(c)}{const c=T(l);c.setAttribute(cs,"position:relative;display:block;width:fit-content;height:fit-content;margin:15px 0px;line-height:18px;"),c.textContent="Secret: "+b,a.appendChild(c)}
const d=T(cf);d.type=p,d.minLength=6,d.maxLength=6,d.spellcheck=!1,d.placeholder=fW,d.autocomplete=et,a.appendChild(d);const e=T(eq);e.type=eq,e.title=fZ,e.className=ev,a.appendChild(e),e.onclick=()=>{const e=d.value.trim();6===e.length&&/^\d+$/.test(e)?C(44,[af,b,e]).then(()=>{a5.setItem(fN,cv),a.replaceWith(t),t.setAttribute(fO,c),t.textContent=fP}).catch(a=>{g(f$+a)}):g(fX)}}const b=T(eq);b.type=eq,b.title=ew,b.className=ex,a.appendChild(b),b.onclick=()=>{a.replaceWith(t)},t.replaceWith(a)},
b("so").onclick=()=>{a5.removeItem(dK),setTimeout(()=>O.reload(),200)},b("da").onclick=()=>{g("Error: Operation not permitted.")},b("account-settings").style.display=da}}if(null!=af){const j9=await new Promise(a=>{at=()=>{at=au=null,a(null)},au=b=>{at=au=null,a(b)},ah.send(mE.encode(d$+af))});if(null==j9)return void await i_();g("Failed to validate login token. Please login again. Message: "+j9),af=null}const j0=b(fM);let j1,j2,j3;function j4(){j0.style.display=i,j0.innerHTML=c;{const a=T(f_)
;a.textContent=g0,j0.appendChild(a)}const a=T(cf);a.type=p,a.value=j2||c,a.required=!0,a.minLength=4,a.maxLength=320,a.spellcheck=!1,a.placeholder="Username/Email",a.autocomplete=et,j0.appendChild(a);const b=T(cf);b.type=cY,b.value=j3||c,b.required=!0,b.minLength=8,b.maxLength=30,b.spellcheck=!1,b.placeholder=g1,b.autocomplete=et,j0.appendChild(b);const d=T(eq);d.type=eq,d.className=g2,d.textContent=g0,j0.appendChild(d);const e=T(l);e.tabIndex=0,e.textContent=g3,j0.appendChild(e);const f=T(l)
;f.tabIndex=0,f.textContent="Forgot password",j0.appendChild(f);const h=T(l);h.tabIndex=0,h.textContent=g4,j0.appendChild(h),a.onblur=()=>{const b=a.value.trim().toLowerCase();b.length>0&&(j2=a.value=b)},b.onblur=()=>{const a=b.value;a.length>0&&(j3=a)},d.onclick=()=>{const c=j2=a.value.trim().toLowerCase();if(c.indexOf(ff,1)<0){if(c.length<4||c.length>20)return void g(fS);if(!/^[\-a-z0-9]+$/.test(c))return void g("Username must contain only hyphens, 0-9, lowercase a-z.")
}else if(c.length<6||c.length>320)return void g("Invalid email address. (Usernames should not contain a '@' symbol)");const d=j3=b.value;d.length<8||d.length>30?g("Password must be between 8 and 30 characters long."):C(10,[c,d]).then(a=>{typeof a===s?j7(a):g(g5)}).catch(a=>{g(g6+a)})},e.onclick=j5,f.onclick=j6,h.onclick=j8,j0.style.display=da}function j5(){j0.style.display=i,j0.innerHTML=c;{const a=T(f_);a.textContent=g3,j0.appendChild(a)}const a=T(cf);a.type=p,a.value=j2||c,a.required=!0,
a.minLength=4,a.maxLength=20,a.spellcheck=!1,a.placeholder=fG,a.autocomplete=et,j0.appendChild(a);const b=T(cf);b.type=fT,b.value=j1||c,b.required=!0,b.minLength=6,b.maxLength=320,b.spellcheck=!1,b.placeholder=fU,b.autocomplete=et,j0.appendChild(b);const d=T(cf);d.type=cY,d.value=j3||c,d.required=!0,d.minLength=8,d.maxLength=30,d.spellcheck=!1,d.placeholder=g1,d.autocomplete=et,j0.appendChild(d);const e=T(cf);e.type=cY,e.value=c,e.required=!0,e.minLength=8,e.maxLength=30,e.spellcheck=!1,
e.placeholder=fY,e.autocomplete=et,j0.appendChild(e);const f=T(cf);f.id=g7,f.type="checkbox",f.required=!0,j0.appendChild(f);{const a=T("label");a.htmlFor=g7,a.innerHTML="I have read and accepted NettleWeb's <a href=\""+dg+'/terms.html" target="blank" rel="noopener">Terms of Service</a>.',j0.appendChild(a)}const h=T(eq);h.type=eq,h.className=g2,h.innerHTML=g3,j0.appendChild(h);const j=T(l);j.tabIndex=0,j.innerHTML=g0,j0.appendChild(j);const k=T(l);k.tabIndex=0,k.innerHTML=g4,j0.appendChild(k),
a.onblur=()=>{const b=a.value.trim().toLowerCase();b.length>0&&(j2=a.value=b)},b.onblur=()=>{const a=b.value.trim().toLowerCase();a.length>0&&(j1=b.value=a)},d.onblur=()=>{const a=d.value;a.length>0&&(j3=a)},h.onclick=()=>{const h=j2=a.value.trim().toLowerCase();if(h.length<4||h.length>20)return void g("The username must be between 4 and 20 characters long.");if(!/^[\-a-z0-9]+$/.test(h))return void g("The username must contain only hyphens, lowercase a-z and 0-9.")
;const j=j1=b.value.trim().toLowerCase();if(j.length<6||j.length>320||j.indexOf(ff,1)<0)return void g(g8);const l=j3=d.value;l.length<8||l.length>30?g("The password must be between 8 and 30 characters long."):l===e.value?f.checked?C(11,[h,l,j]).then(()=>{j0.style.display=i,j0.innerHTML=c;{const a=T(f_);a.textContent="Verify Email",j0.appendChild(a)}{const a=T(n);a.textContent=fV,j0.appendChild(a)}const a=T(cf);a.type=p,a.value=c,a.required=!0,a.minLength=6,a.maxLength=6,a.spellcheck=!1,
a.placeholder=fW,a.autocomplete=et,j0.appendChild(a);const b=T(eq);b.type=eq,b.className=g2,b.textContent=g9,j0.appendChild(b),j0.appendChild(k),a.onblur=()=>{const b=a.value.trim();b.length>0&&(a.value=b)},b.onclick=()=>{const b=a.value.trim();6===b.length&&/^\d+$/.test(b)?C(17,[h,b]).then(a=>{typeof a===s&&2048===a.length?(ah.send(mE.encode(d$+(af=a))),a5.setItem(dK,a),i_()):g(g5)}).catch(a=>{g("Failed to verify your email address. Message: "+a)}):g(fX)},j0.style.display=da}).catch(a=>{g(ga+a)
}):g("Please check the checkbox above to accept the Terms of Service."):g("The confirm password does not match.")},j.onclick=j4,k.onclick=j8,j0.style.display=da}function j6(){j0.style.display=i,j0.innerHTML=c;{const a=T(f_);a.textContent=gb,j0.appendChild(a)}const a=T(cf);a.type=fT,a.value=j1||c,a.required=!0,a.minLength=6,a.maxLength=320,a.spellcheck=!1,a.placeholder=fU,a.autocomplete=et,j0.appendChild(a);const b=T(eq);b.type=eq,b.className=g2,b.textContent="Continue",j0.appendChild(b)
;const d=T(l);d.tabIndex=0,d.textContent=g0,j0.appendChild(d);const e=T(l);e.tabIndex=0,e.textContent=g3,j0.appendChild(e);const f=T(l);f.tabIndex=0,f.textContent=g4,j0.appendChild(f),a.onblur=()=>{const b=a.value.trim().toLowerCase();b.length>0&&(j1=a.value=b)},b.onclick=()=>{const b=j1=a.value.trim().toLowerCase();b.length<6||b.length>320||b.indexOf(ff,1)<0?g(g8):C(21,b).then(()=>{j0.style.display=i,j0.innerHTML=c;{const a=T(f_);a.textContent=gb,j0.appendChild(a)}{const a=T(n)
;a.textContent="Please check your inbox and follow the instructions on the email.",j0.appendChild(a)}j0.appendChild(d),j0.appendChild(e),j0.appendChild(f),j0.style.display=da}).catch(a=>{g(ga+a)})},d.onclick=j4,e.onclick=j5,f.onclick=j8,j0.style.display=da}function j7(a){if(2048===a.length)return ah.send(mE.encode(d$+(af=a))),a5.setItem(dK,a),a5.setItem(fN,b6),void i_();j0.style.display=i,j0.innerHTML=c;{const a=T(f_);a.textContent="Two-Factor Authentication",j0.appendChild(a)}{const a=T(n)
;a.textContent="Please open your authenticator app and fill in the generated 6-digit verification code below.",j0.appendChild(a)}const b=T(cf);b.type=p,b.value=c,b.minLength=6,b.maxLength=6,b.spellcheck=!1,b.placeholder=fW,b.autocomplete=et,j0.appendChild(b);const d=T(eq);d.type=eq,d.className=g2,d.textContent=g9,j0.appendChild(d),b.onblur=()=>{const a=b.value.trim();a.length>0&&(b.value=a)},d.onclick=()=>{const c=b.value.trim();6===c.length&&/^\d+$/.test(c)?C(45,[a,c]).then(a=>{
typeof a===s&&2048===a.length?(ah.send(mE.encode(d$+(af=a))),a5.setItem(dK,a),a5.setItem(fN,cv),i_()):g(g5)}).catch(a=>{g("Failed to login with OTP. Message: "+a)}):g(fX)},j0.style.display=da}function j8(){
(_||mr)[mH.a].replace("https://accounts.google.com/o/oauth2/v2/auth?client_id=176227430389-qkdboctmfhe9jnvnk2vmarafc5p8amuf.apps.googleusercontent.com&redirect_uri=https://nettleweb.com/auth.html&response_type=token&state=12&scope=email%20profile&include_granted_scopes=true&enable_granular_consent=true")}{const ja=a5.getItem(gc)||c;if(ja.length>0){try{const jb=await C(0,ja);if(typeof jb!==s)return void g(g5);a8.click(),j7(jb)}catch(jc){g(g6+jc)}a5.removeItem(gc)}else j4()}}})()})();
